<<<<<<< HEAD
"""
This type stub file was generated by pyright.
"""

fonts = ...
=======
"""
This type stub file was generated by pyright.
"""

fonts = ...
>>>>>>> d00dbf53af6d949b5f6cb7562208f2d8edd318d2
