"""
This type stub file was generated by pyright.
"""

from typing import Any, Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    ...
class _InnerMethods(Protocol):
    hwp: Any
    def get_cell_addr(self, str) -> tuple[int]:
        ...
    
    def get_pos(self) -> tuple[int]:
        ...
    
    def get_message_box_mode(self) -> int:
        ...
    
    def set_message_box_mode(self, mode: int) -> int:
        ...
    
    @property
    def HParameterSet(self): # -> None:
        ...
    


class RunMethods(_InnerMethods):
    """
    Run 메서드 모음
    """
    def ASendBrowserText(self) -> bool:
        """
        웹브라우저로 보내기
        """
        ...
    
    def AutoChangeHangul(self) -> bool:
        """
        구버전의 "낱자모 우선입력" 활성화 토글기능. 현재는 사용하지 않으며, 최신버전에서 <도구-글자판-글자판 자동 변경(A)> 기능에 통합되었다.낱자모 우선입력 기능은 제거된 것으로 보임

        """
        ...
    
    def AutoChangeRun(self) -> bool:
        """
        위 커맨드를 실행할 때마다 "글자판 자동 변경 기능"이 활성화/비활성화로 토글된다. 다만 API 등으로 텍스트를 입력하는 경우 원래 한/영 자동변환이 되지 않으므로, 자동화에는 쓰일 일이 없는 액션.
        """
        ...
    
    def AutoSpellRun(self) -> bool:
        """
        맞춤법 도우미(맞춤법이 틀린 단어 밑에 빨간 점선) 활성화/비활성화를 토글한다. 실행 후(비활성화시) 몇 초 뒤에 붉은 줄이 사라지는 것을 확인할 수 있다. 중간 스페이스에 유의.
        """
        ...
    
    def AutoSpellSelect0(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect1(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect2(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect3(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect4(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect5(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect6(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect7(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect8(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect9(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect10(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect11(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect12(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect13(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect14(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect15(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def AutoSpellSelect16(self) -> bool:
        """
        맞춤법 도우미를 통해, 미리 입력되어 있는 어휘로 변경하는 액션. 어휘는 0에서부터 최대 16번 인덱스까지 존재. 예를 들어 아래 "aaple"이라는 오타의 경우 0~9까지 10개의 슬롯에 네 개의 어휘(ample, maple, apple, leap)만 랜덤하게 나타난다.

        """
        ...
    
    def BottomTabFrameClose(self) -> bool:
        """아래쪽 작업창 감추기"""
        ...
    
    def BreakColDef(self) -> bool:
        """
        다단 레이아웃을 사용하는 경우의 "단 정의 삽입 액션(Ctrl-Alt-Enter)".

        단 정의 삽입 위치를 기점으로 구분된 다단을 하나 추가한다.
        다단이 아닌 경우에는 일반 "문단나누기(Enter)"와 동일하다.
        """
        ...
    
    def BreakColumn(self) -> bool:
        """
        다단 레이아웃을 사용하는 경우 "단 나누기[배분다단] 액션(Ctrl-Shift-Enter)".

        단 정의 삽입 위치를 기점으로 구분된 다단을 하나 추가한다.
        다단이 아닌 경우에는 일반 "문단나누기(Enter)"와 동일하다.

        """
        ...
    
    def BreakLine(self) -> bool:
        """
        라인나누기 액션(Shift-Enter).

        들여쓰기나 내어쓰기 등 문단속성이 적용되어 있는 경우에
        속성을 유지한 채로 줄넘김만 삽입한다. 이 단축키를 모르고 보고서를 작성하면,
        들여쓰기를 맞추기 위해 스페이스를 여러 개 삽입했다가,
        앞의 문구를 수정하는 과정에서 스페이스 뭉치가 문단 중간에 들어가버리는 대참사가 자주 발생할 수 있다.
        """
        ...
    
    def BreakPage(self) -> bool:
        """
        쪽 나누기 액션(Ctrl-Enter).

        캐럿 위치를 기준으로 하단의 글을 다음 페이지로 넘긴다.
        BreakLine과 마찬가지로 보고서 작성시 자주 사용해야 하는 액션으로,
        이 기능을 사용하지 않고 보고서 작성시 엔터를 십여개 치고 다음 챕터 제목을 입력했다가,
        일부 수정하면서 챕터 제목이 중간에 와 있는 경우 등의 불상사가 발생할 수 있다.
        """
        ...
    
    def BreakPara(self) -> bool:
        """
        줄바꿈(문단 나누기). 일반적인 엔터와 동일하다.

        Returns:
            True

        Examples:
            >>> from pyhwpx import Hwp
            >>> hwp = Hwp()  # 한/글 창이 열림
            >>> hwp.BreakPara()  # 줄바꿈 삽입!
            True
            >>> hwp.insert_text("\\r\\n")  # BreakPara와 동일
            True
        """
        ...
    
    def BreakSection(self) -> bool:
        """
        구역[섹션] 나누기 액션(Shift-Alt-Enter). 새로 생성된 섹션에서는 편집용지를 다르게 설정하거나, 혹은 새 개요번호/모양을 만든다든지 할 수 있다. 단, 초깃값으로 새 섹션이 생성되는 게 아니라, 기존 섹션의 편집용지, 바탕쪽 상태, 각주/미주 모양, 프레젠테이션 상태, 쪽 테두리/배경 속성 및 단 모양 등 대부분을 그대로 이어받으며, 새 섹션에서 수정시 기존 섹션에는 대부분 영향을 미치지 않는다.

        """
        ...
    
    def Cancel(self) -> bool:
        """
        취소 액션. Esc 키를 눌렀을 때와 동일하다. 대표적인 예로는 텍스트 선택상태나 셀선택모드  해제 또는 이미지, 표 등의 개체 선택을 취소할 때 사용한다. Cancel 과 유사하게 쓰이는 액션으로 Close(또는 CloseEx, Shift-Esc)가 있다.

        """
        ...
    
    def CaptureHandler(self) -> bool:
        """
        갈무리 시작 액션. 현재 버전에서는 Run커맨드로 사용할 수 없는 것 같다. 어떤 이미지포맷으로 저장하든 오류발생.

        """
        ...
    
    def CaptureDialog(self) -> bool:
        """
        갈무리 끝 액션. 현재 버전에서는 Run커맨드로 사용할 수 없는 것 같다. 어떤 이미지포맷으로 저장하든 오류발생.

        """
        ...
    
    def ChangeSkin(self) -> bool:
        """스킨 바꾸기"""
        ...
    
    def CharShapeBold(self) -> bool:
        """
        글자모양 중 "진하게Bold" 속성을 토글하는 액션. 이 액션을 실행하기 전에 특정 셀이나 텍스트가 선택된 상태여야 하며, 이 커맨드만으로는 확실히 "진하게" 속성이 적용되었는지 확인할 수 없다. 그 이유는 토글 커맨드라서, 기존에 진하게 적용되어 있었다면, 해제되어버리기 때문이다. 확실히 진하게를 적용하는 방법으로는, 초기에 모든 텍스트의 진하게를 해제(진하게 두 번??)한다든지, 파라미터셋을 활용하여 진하게 속성이 적용되어 있는지를 확인하는 방법 등이 있다.

        """
        ...
    
    def CharShapeCenterline(self) -> bool:
        """
        글자에 취소선 적용을 토글하는 액션. Bold와 마찬가지로 토글이므로, 기존에 취소선이 적용되어 있다면 해제되어버리므로 사용에 유의해야 한다.

        """
        ...
    
    def CharShapeEmboss(self) -> bool:
        """
        글자모양에 양각 속성(글자가 튀어나온 느낌) 적용을 토글한다.

        """
        ...
    
    def CharShapeEngrave(self) -> bool:
        """
        글자모양에 음각 속성(글자가 움푹 들어간 느낌) 적용을 토글한다.

        """
        ...
    
    def CharShapeHeight(self) -> bool:
        """
        글자모양(Alt-L) 대화상자를 열고, 포커스를 "기준 크기"로 이동한다. (수작업이 필요하므로 자동화에 사용하지는 않는다. 유사한 액션으로 글꼴 언어를 선택하는 CharShapeLang, CharShapeSpacing, CharShapeTypeFace, CharShapeWidth 등이 있다.)

        """
        ...
    
    def CharShapeHeightDecrease(self) -> bool:
        """
        글자 크기를 1포인트씩 작게 한다. 단, 속도가 다소 느리므로.. 큰 폭으로 조정할 때에는 다른 방법을 쓰는 것을 추천.

        """
        ...
    
    def CharShapeHeightIncrease(self) -> bool:
        """
        글자 크기를 1포인트씩 크게 한다. 단, 속도가 다소 느리므로.. 큰 폭으로 조정할 때에는 다른 방법을 쓰는 것을 추천.

        """
        ...
    
    def CharShapeItalic(self) -> bool:
        """
        글자 모양에 이탤릭 속성을 토글한다.

        """
        ...
    
    def CharShapeLang(self) -> bool:
        """글자 언어"""
        ...
    
    def CharShapeNextFaceName(self) -> bool:
        """
        다음 글꼴로 이동(Shift-Alt-F)한다. 단, 이 액션으로 어떤 폰트가 선택되었는지를 파이썬에서 확인하려면 파라미터셋에 접근해야 한다. 유사한 커맨드로, CharShapePrevFaceName 이 있다.

        """
        ...
    
    def CharShapeNormal(self) -> bool:
        """
        글자모양에 적용된 속성 및 글자색 등 전부를 해제(Shift-Alt-C)한다. 단 글꼴, 크기 등은 바뀌지 않는다.

        """
        ...
    
    def CharShapeOutline(self) -> bool:
        """
        글자모양의 외곽선 속성을 토글한다.

        """
        ...
    
    def CharShapePrevFaceName(self) -> bool:
        """
        이전 글꼴 ALT+SHIFT+G
        """
        ...
    
    def CharShapeShadow(self) -> bool:
        """
        선택한 텍스트 글자모양 중 그림자 속성을 토글한다.

        """
        ...
    
    def CharShapeSpacing(self) -> bool:
        """
        글자모양(alt-L) 창을 열고, 자간 값에 포커스를 옮긴다.
        """
        ...
    
    def CharShapeSpacingDecrease(self) -> bool:
        """
        자간을 1%씩 좁힌다. 최대 -50%까지 좁힐 수 있다. 다만 자동화 작업시 줄넘김을 체크하는 것이 상당히 번거로운 작업이므로, 크게 보고서의 틀이 바뀌지 않는 선에서는 자간을 좁히는 것보다 "한 줄로 입력"을 활용하는 편이 간단하고 자연스러울 수 있다. 한 줄로 입력 옵션 : 문단모양(Alt-T)의 확장 탭에 있음. 한 줄로 입력을 활성화해놓은 문단이나 셀에서는 자간이 아래와 같이 자동으로 좁혀진다.

        """
        ...
    
    def CharShapeSpacingIncrease(self) -> bool:
        """
        자간을 1%씩 넓힌다. 최대 50%까지 넓힐 수 있다.

        """
        ...
    
    def CharShapeSubscript(self) -> bool:
        """
        선택한 텍스트에 아래첨자 속성을 토글(Shift-Alt-S)한다.

        """
        ...
    
    def CharShapeSuperscript(self) -> bool:
        """
        선택한 텍스트에 위첨자 속성을 토글(Shift-Alt-P)한다.

        """
        ...
    
    def CharShapeSuperSubscript(self) -> bool:
        """
        선택한 텍스트의 첨자속성을 위→아래→보통의 순서를 반복해서 토글한다.

        """
        ...
    
    def CharShapeTextColorBlack(self) -> bool:
        """
        선택한 텍스트의 글자색을 검정색으로 변경한다.

        """
        ...
    
    def CharShapeTextColorBlue(self) -> bool:
        """
        선택한 텍스트의 글자색을 파란색으로 변경한다.

        """
        ...
    
    def CharShapeTextColorBluish(self) -> bool:
        """
        선택한 텍스트의 글자색을 청록색으로 변경한다.

        """
        ...
    
    def CharShapeTextColorGreen(self) -> bool:
        """
        선택한 텍스트의 글자색을 초록색으로 변경한다.

        """
        ...
    
    def CharShapeTextColorRed(self) -> bool:
        """
        선택한 텍스트의 글자색을 빨간색으로 변경한다.

        """
        ...
    
    def CharShapeTextColorViolet(self) -> bool:
        """
        선택한 텍스트의 글자색을 보라색으로 변경한다.

        """
        ...
    
    def CharShapeTextColorWhite(self) -> bool:
        """
        선택한 텍스트의 글자색을 흰색으로 변경한다.

        """
        ...
    
    def CharShapeTextColorYellow(self) -> bool:
        """
        선택한 텍스트의 글자색을 노란색으로 변경한다.

        """
        ...
    
    def CharShapTypeface(self) -> bool:
        """글자 모양 (실행 안됨)"""
        ...
    
    def CharShapeUnderline(self) -> bool:
        """
        선택한 텍스트에 밑줄 속성을 토글한다. 대소문자에 유의해야 한다. (UnderLine이 아니다.)

        """
        ...
    
    def CharShapeWidth(self) -> bool:
        """글자 모양(Alt-L) 창에서 글자 장평에 포커스를 둔다."""
        ...
    
    def CharShapeWidthDecrease(self) -> bool:
        """
        장평을 1%씩 줄인다. 장평 범위는 50~200%이며, 장평을 늘일 때는 Decrease 대신 Increase를 사용하면 된다.

        """
        ...
    
    def CharShapeWidthIncrease(self) -> bool:
        """
        장평을 1%씩 줄인다. 장평 범위는 50~200%이며, 장평을 줄일 때는 Increase 대신 Decrease를 사용하면 된다.

        """
        ...
    
    def CloseEx(self) -> bool:
        """
        현재 리스트를 닫고 상위 리스트로 이동하는 액션.

        Close와 CloseEx는 유사하나 두 가지 차이점이 있다.
        첫 번째로는 여러 계층의 표 안에서 CloseEx 실행시
        본문이 아니라 상위의 표(셀)로 캐럿이 단계적으로 이동한다는 점.
        반면 Close는 무조건 본문으로 나간다.
        두 번째로, CloseEx에는 전체화면(최대화 말고)을 해제하는 기능이 있다.
        Close로는 전체화면 해제가 되지 않는다.
        사용빈도가 가장 높은 액션 중의 하나라고 생각한다.
        """
        ...
    
    def Comment(self) -> bool:
        """
        새로운 숨은설명 컨트롤을 만들고, 해당 숨은설명으로 이동.

        아래아한글에 "숨은 설명"이 있다는 걸 아는 사람도 없다시피 한데,
        그 "숨은 설명" 관련한 Run 액션이 세 개나 있다.
        Comment 액션은 표현 그대로 숨은 설명을 붙일 수 있다.
        텍스트만 넣을 수 있을 것 같은 액션이름인데,
        사실 표나 그림도 자유롭게 삽입할 수 있기 때문에,
        문서 안에 몰래 숨겨놓은 또다른 문서 느낌이다.
        파일별로 자동화에 활용할 수 있는 특정 문자열을
        파이썬이 아니라 숨은설명 안에 붙여놓고 활용할 수도 있지 않을까
        이런저런 고민을 해봤는데, 개인적으로 자동화에 제대로 활용한 적은 한 번도 없었다.
        숨은 설명이라고 민감한 정보를 넣으면 안 되는데,
        완전히 숨겨져 있는 게 아니기 때문이다.
        현재 캐럿위치에 [숨은설명] 조판부호가 삽입되며,
        이를 통해 숨은 설명 내용이 확인 가능하므로 유념해야 한다.
        재미있는 점은, 숨은설명 안에 또 숨은설명을 삽입할 수 있다.
        숨은설명 안에다 숨은설명을 넣고 그 안에 또 숨은설명을 넣는...
        이런 테스트를 해봤는데 2,400단계 정도에서 한글이 종료돼버렸다.

        Returns:
            성공시 True, 실패시 False를 리턴.
        """
        ...
    
    def CommentDelete(self) -> bool:
        """
        숨은설명 지우기

        단어 그대로 숨은 설명을 지우는 액션이다.
        단, 사용방법이 까다로운데 숨은 설명 안에 들어가서 CommentDelete를 실행하면,
        지울지 말지(Yes/No) 팝업이 나타난다.
        나중에 자세히 설명하겠지만 이런 팝업을 자동처리하는 방법은 hwp.SetMessageBoxMode() 메서드를 미리 실행해놓는 것이다.
        Yes/No 방식의 팝업에서 Yes를 선택하는 파라미터는 0x10000 (또는 65536)이므로,
        hwp.SetMessageBoxMode(0x10000) 를 사용하면 된다.
        """
        ...
    
    def CommentModify(self) -> bool:
        """
        숨은설명 수정하기

        단어 그대로 숨은 설명을 수정하는 액션이다.
        캐럿은 해당 [숨은설명] 조판부호 바로 앞에 위치하고 있어야 한다.

        """
        ...
    
    def Copy(self) -> bool:
        """
        복사하기. (비추천)

        선택되어 있는 문자열 혹은 개체(표, 이미지 등)를 클립보드에 저장한다.
        파이썬에서 클립보드를 다루는 모듈은 pyperclip이나,
        pywin32의 win32clipboard 두 가지가 가장 많이 쓰이는데,
        단순한 문자열의 경우 hwp.Copy() 실행 후 pyperclip.paste()로 파이썬으로 가져올 수 있지만,
        서식 등의 메타 정보를 모두 잃어버린다.

        또한 빠른 반복작업시 윈도우OS의 클립보드 잠금 때문에 오류가 발생할 수 있다.

        hwp.Copy()나 hwp.Paste() 대신 hwp.GetTextFile()이나 hwp.save_block_as 등의 메서드를 사용하는 것을 추천.

        """
        ...
    
    def CopyPage(self) -> bool:
        """
        쪽 복사

        한글2014 이하의 버전에서는 사용할 수 없다.
        """
        ...
    
    def CustCopyBtn(self) -> bool:
        """툴바 버튼 복사하기"""
        ...
    
    def CustCutBtn(self) -> bool:
        """툴바 버튼 오려두기"""
        ...
    
    def CustEraseBtn(self) -> bool:
        """툴바 버튼 지우기"""
        ...
    
    def CustInsSepBtn(self) -> bool:
        """툴바 버튼에 구분선 넣기"""
        ...
    
    def CustomizeToolbar(self) -> bool:
        """도구상자 사용자 설정"""
        ...
    
    def CustPasteBtn(self) -> bool:
        """툴바 버튼 붙여기"""
        ...
    
    def CustRenameBtn(self) -> bool:
        """툴바 버튼 이름 바꾸기"""
        ...
    
    def CustRestBtn(self) -> bool:
        """툴바 버튼 처음 상태로 되돌리기"""
        ...
    
    def CustViewIconBtn(self) -> bool:
        """툴바 버튼 아이콘만 보이기"""
        ...
    
    def CustViewIconNameBtn(self) -> bool:
        """툴바 버튼 이름과 아이콘 보이기"""
        ...
    
    def CustViewNameBtn(self) -> bool:
        """툴바 버튼 이름만 보이기"""
        ...
    
    def DeleteField(self) -> bool:
        """
        누름틀지우기.

        누름틀 안의 내용은 지우지 않고, 단순히 누름틀만 지운다.
        지울 때 캐럿의 위치는 누름틀 안이든, 앞이나 뒤든 붙어있기만 하면 된다.
        만약 최종문서에는 누름틀을 넣지 않고
        모두 일반 텍스트로 변환하려고 할 때
        이 기능을 활용하면 된다.

        Returns:
            성공시 True, 실패시 False를 리턴.

        """
        ...
    
    def DeleteFieldMemo(self) -> bool:
        """
        메모 지우기. 누름틀 지우기와 유사하다. 메모 누름틀에 붙어있거나, 메모 안에 들어가 있는 경우 위 액션 실행시 해당 메모가 삭제된다.

        """
        ...
    
    def DeletePage(self) -> bool:
        """
        쪽 지우기

        한글2014 이하의 버전에서는 사용할 수 없다.

        """
        ...
    
    def DrawObjCancelOneStep(self) -> bool:
        """
        다각형(곡선) 그리는 중 이전 선 지우기.

        현재 사용 안함(?)

        """
        ...
    
    def DrawObjEditDetail(self) -> bool:
        """
        그리기 개체 중 다각형 점편집 액션.

        다각형이 선택된 상태에서만 실행가능.

        """
        ...
    
    def DrawObjOpenClosePolygon(self) -> bool:
        """
        닫힌 다각형 열기 또는 열린 다각형 닫기 토글.

        ①다각형 개체 선택상태가 아니라 편집상태에서만 위 명령어가 실행된다.

        ②닫힌 다각형을 열 때는 마지막으로 봉합된 점에서 아주 조금만 열린다.

        ③아주 조금만 열린 상태에서 닫으면 노드(꼭지점)가 추가되지 않지만, 적절한 거리를 벌리고 닫기를 하면 추가됨.

        """
        ...
    
    def DrawObjTemplateSave(self) -> bool:
        """
        그리기개체를 그리기마당에 템플릿으로 등록하는 액션

        (어떻게 써먹고 싶어도 방법을 모르겠다...)
        그리기개체가 선택된 상태에서만 실행 가능하다.
        여담으로, 그리기 마당에 임의로 등록한 개체 삭제 아이콘을 못 찾고 있는데;
        한글2020 기준으로, 개체 이름을 "얼굴"이라고 "기본도형"에 저장했을 경우,
        찾아가서 아래의 파일을 삭제해도 된다.
        `"C:/Users/이름/AppData/Roaming/HNC/User/Shared110/HwpTemplate/Draw/FG_Basic_Shapes/얼굴.drt"`

        """
        ...
    
    def EasyFind(self) -> bool:
        """
        쉬운 찾기

        사용하지 않음.

        """
        ...
    
    def EditFieldMemo(self) -> bool:
        """
        메모 내용 편집 액션.

        "메모 내용 보기" 창이 하단에 열린다.
        SplitMemoOpen과 동일한 기능으로 보이며,
        메모내용보기창에서 두 번째 이후의 메모 클릭시 메모내용 보기 창이 닫히는 버그가 있다.(한/글 2020 기준)참고로 메모내용 보기 창을 닫을 때는 SplitMemoClose 커맨드를 쓰면 된다.

        Returns:
            성공시 True, 실패시 False를 리턴
        """
        ...
    
    def Erase(self) -> bool:
        """
        선택한 문자나 개체 삭제.

        문자열이나 컨트롤 등을 삭제한다는 점에서는 Delete나 DeleteBack과 유사하지만,
        가장 큰 차이점은, 아무 것도 선택되어 있지 않은 상태일 때 Erase는 아무 것도 지우지 않는다는 점이다.
        (Delete나 DeleteBack은 어찌됐든 앞뒤의 뭔가를 지운다.)

        Returns:
            성공시 True, 실패시 False를 리턴
        """
        ...
    
    def FileClose(self) -> bool:
        """
        문서 닫기.

        저장 이후 변경사항이 있으면 팝업이 뜨므로 주의
        """
        ...
    
    def FileFind(self) -> bool:
        """문서 찾기"""
        ...
    
    def FileNew(self) -> bool:
        """
        새 문서 창을 여는 명령어.

        참고로 현재 창에서 새 탭을 여는 명령어는 ``hwp.FileNewTab()``

        여담이지만 한/글2020 기준으로 새 창은 30개까지 열 수 있다.
        그리고 한 창에는 탭을 30개까지 열 수 있다.
        즉, (리소스만 충분하다면) 동시에 열어서 자동화를 돌릴 수 있는
        문서 갯수는 900개!
        """
        ...
    
    def FileNewTab(self) -> bool:
        """
        새 탭을 여는 명령어.
        """
        ...
    
    def FileNextVersionDiff(self) -> bool:
        """버전 비교 :　앞으로 이동"""
        ...
    
    def FilePrevVersionDiff(self) -> bool:
        """버전 비교 : 뒤로 이동"""
        ...
    
    def FileOpen(self) -> bool:
        """
        문서를 여는 명령어.

        단 파일선택 팝업이 뜨므로,
        자동화작업시에는 이 명령어를 사용하지 않는다.
        대신 hwp.open(파일명)을 사용해야 한다.
        """
        ...
    
    def FileOpenMRU(self) -> bool:
        """
        최근 작업문서 열기

        현재는 FileOpen과 동일한 동작을 하는 것으로 보임.
        사용자입력을 요구하는 팝업이 뜨므로
        자동화에 사용하지 않으며, hwp.open(Path)을 써야 한다.

        """
        ...
    
    def FilePreview(self) -> bool:
        """
        미리보기 창을 열어준다.

        자동화와 큰 연관이 없어 자주 쓰이지도 않고,
        더군다나 닫는 명령어가 없다.
        또한 이 명령어는 hwp.XHwpDocuments.Item(0).XHwpPrint.RunFilePreview()와 동일한 동작을 하는데,
        재미있는 점은,

            - ①스크립트 매크로 녹화 진행중에 ``hwp.FilePreview()``는 실행해도 반응이 없고, 녹화 로그에도 잡히지 않는다.
            - ②그리고 스크립트매크로 녹화 진행중에 [파일] - [미리보기(V)] 메뉴도 비활성화되어 있어 코드를 알 수 없다.
            - ③그런데 hwp.XHwpDocuments.Item(0).XHwpPrint.RunFilePreview()는 녹화중에도 실행이 된다. 녹화된 코드와 관련하여 남기고 싶은 코멘트가 많은데, 별도의 포스팅으로 남길 예정.
        """
        ...
    
    def FileQuit(self) -> bool:
        """
        한/글 프로그램을 종료한다.

        단, 저장 이후 문서수정이 있는 경우에는 팝업이 뜨므로,
        ①저장하거나 ②수정내용을 버리는 메서드를 활용해야 한다.

        """
        ...
    
    def FileSave(self) -> bool:
        """
        문서 저장(Alt-S).

        가급적 ``hwp.save()``를 사용하자.
        ``hwp.save()``와 ``hwp.FileSave()``에 차이가 있는데
        ``hwp.save()``는 실제 변경이 없으면 저장을 수행하지 않지만
        ``hwp.FileSave()``는 변경이 없어도 저장을 수행하므로 수정일자가 바뀐다.
        """
        ...
    
    def FileSaveAs(self) -> bool:
        """
        다른 이름으로 저장(Alt-V).

        사용자입력을 필요로 하므로 이 액션은 사용하지 않는다.
        대신 hwp.save_as(Path)를 사용하면 된다.

        """
        ...
    
    def FileSaveAsDRM(self) -> bool:
        """배포용 문서로 저장하기"""
        ...
    
    def FileVersionDiffChangeAlign(self) -> bool:
        """버전 비교 : 비교화면 배열 변경 (좌우↔상하)"""
        ...
    
    def FileVersionDiffSameAlign(self) -> bool:
        """버전 비교 : 비교화면 다시 정렬"""
        ...
    
    def FileVersionDiffSyncScroll(self) -> bool:
        """버전 비교 : 비교화면 동시에 이동"""
        ...
    
    def FillColorShadeDec(self) -> bool:
        """면색 음영 비율 감소"""
        ...
    
    def FillColorShadeInc(self) -> bool:
        """면색 음영 비율 증가"""
        ...
    
    def FindForeBackBookmark(self) -> bool:
        """
        책갈피 찾아가기.

        사용자 입력을 요구하므로 자동화에는 사용하지 않는다.

        """
        ...
    
    def FindForeBackCtrl(self) -> bool:
        """
        조판부호 찾아가기.

        사용자 입력을 요구하므로 자동화에는 사용하지 않는다.
        참고로 ``hwp.FindForeBackSelectCtrl``은 선택.
        """
        ...
    
    def FindForeBackFind(self) -> bool:
        """
        찾기.

        사용자 입력을 요구하므로 자동화에는 사용하지 않는다.

        """
        ...
    
    def FindForeBackLine(self) -> bool:
        """
        줄 찾아가기.

        사용자 입력을 요구하므로 자동화에는 사용하지 않는다.

        """
        ...
    
    def FindForeBackPage(self) -> bool:
        """
        쪽 찾아가기.

        사용자 입력을 요구하므로 자동화에는 사용하지 않는다.

        """
        ...
    
    def FindForeBackSection(self) -> bool:
        """
        구역 찾아가기.

        사용자 입력을 요구하므로 자동화에는 사용하지 않는다.

        """
        ...
    
    def FindForeBackSelectCtrl(self) -> bool:
        """앞뒤로 찾아가기 : 조판 부호 찾기 (선택)"""
        ...
    
    def FindForeBackStyle(self) -> bool:
        """
        스타일 찾아가기.

        사용자 입력을 요구하므로 자동화에는 사용하지 않는다.

        """
        ...
    
    def FormDesignMode(self) -> bool:
        """양식 개체 디자인 모드 변경"""
        ...
    
    def FormObjCreatorCheckButton(self) -> bool:
        """양식 개체 체크 박스 넣기"""
        ...
    
    def FormObjCreatorComboBox(self) -> bool:
        """양식 개체 콤보 박스 넣기"""
        ...
    
    def FormObjCreatorEdit(self) -> bool:
        """양식 개체 에디트 박스 넣기"""
        ...
    
    def FormObjCreatorPushButton(self) -> bool:
        """양식 개체 푸쉬 버튼 넣기"""
        ...
    
    def FormObjCreatorRadioButton(self) -> bool:
        """양식 개체 라디오 버튼 넣기"""
        ...
    
    def FormObjRadioGroup(self) -> bool:
        """양식 개체 라디오 버튼 그룹 묶기"""
        ...
    
    def FrameFullScreen(self) -> bool:
        """
        한/글 프로그램창 전체화면(창 최대화 아님).

        전체화면 해제는 hwp.FrameFullScreenEnd() 또는 hwp.CloseEx()
        """
        ...
    
    def FrameFullScreenEnd(self) -> bool:
        """전체 화면 닫기"""
        ...
    
    def FrameHRuler(self) -> bool:
        """가로축 눈금자 보이기/감추기"""
        ...
    
    def FrameStatusBar(self) -> bool:
        """
        한/글 프로그램 하단의 상태바 보이기/숨기기 토글

        """
        ...
    
    def FrameViewZoomRibon(self) -> bool:
        """화면 확대/축소"""
        ...
    
    def FrameVRuler(self) -> bool:
        """세로축 눈금자 보이기/감추기"""
        ...
    
    def HancomRoom(self) -> bool:
        """한컴 계약방"""
        ...
    
    def HanThDIC(self) -> bool:
        """
        한/글에 내장되어 있는 "유의어/반의어 사전"을 여는 액션.

        """
        ...
    
    def HeaderFooterDelete(self) -> bool:
        """
        머리말/꼬리말 지우기.

        본문이 아니라 머리말/꼬리말 편집상태에서 실행해야
        삭제 팝업이 뜬다.
        삭제팝업 없이 머리말/꼬리말을 삭제하려면
        hwp.SetMessageBoxMode(0x10000)을 미리 실행해놓아야 한다.

        자동화작업시에는 ``hwp.HeaderFooterModify()``을 통해
        편집상태로 들어가야 한다.

        """
        ...
    
    def HeaderFooterModify(self) -> bool:
        """
        머리말/꼬리말 고치기.

        마우스를 쓰지 않고 머리말/꼬리말 편집상태로 들어갈 수 있다.
        단, 커서가 머리말/꼬리말 컨트롤에 닿아 있는 상태에서 실행해야 한다.
        """
        ...
    
    def HeaderFooterToNext(self) -> bool:
        """
        다음 머리말/꼬리말.

        당장은 사용방법을 모르겠다..
        """
        ...
    
    def HeaderFooterToPrev(self) -> bool:
        """
        이전 머리말.

        당장은 사용방법을 모르겠다..
        """
        ...
    
    def HelpContents(self) -> bool:
        """내용"""
        ...
    
    def HelpIndex(self) -> bool:
        """찾아보기"""
        ...
    
    def HelpWeb(self) -> bool:
        """온라인 고객 지원"""
        ...
    
    def HiddenCredits(self) -> bool:
        """
        인터넷 정보.

        사용방법을 모르겠다.

        """
        ...
    
    def HideTitle(self) -> bool:
        """
        차례 숨기기(Ctrl-K-S)

        ([도구 - 차례/색인 - 차례 숨기기] 메뉴에 대응.
        실행한 개요라인을 자동생성되는 제목차례에서 숨긴다.
        즉시 변경되지 않으며,
        ``hwp.UpdateAllContents()``(모든 차례 새로고침, Ctrl-KA) 실행시
        제목차례가 업데이트된다.
        """
        ...
    
    def HimConfig(self) -> bool:
        """
        입력기 언어별 환경설정.

        현재는 실행되지 않는 듯 하다.
        대신 ``hwp.HimKbdChange()``로 환경설정창을 띄울 수 있다.
        자동화에는 쓰이지 않는다.

        """
        ...
    
    def HimKbdChange(self) -> bool:
        """
        입력기 언어별 환경설정.

        """
        ...
    
    def HorzScrollbar(self) -> bool:
        """가로축 스크롤바 보이기/감추기"""
        ...
    
    def HwpCtrlEquationCreate97(self) -> bool:
        """
        한/글97버전 수식 만들기

        실행되지 않는 듯 하다.

        """
        ...
    
    def HwpCtrlFileNew(self) -> bool:
        """
        한글컨트롤 전용 새문서.

        실행되지 않는 듯 하다.

        """
        ...
    
    def HwpCtrlFileOpen(self) -> bool:
        """
        한글컨트롤 전용 파일 열기.

        실행되지 않는 듯 하다.

        """
        ...
    
    def HwpCtrlFileSave(self) -> bool:
        """
        한글컨트롤 전용 파일 저장.

        실행되지 않는다.

        """
        ...
    
    def HwpCtrlFileSaveAs(self) -> bool:
        """
        한글컨트롤 전용 다른 이름으로 저장.

        실행되지 않는다.

        """
        ...
    
    def HwpCtrlFileSaveAsAutoBlock(self) -> bool:
        """
        한글컨트롤 전용 다른이름으로 블록 저장.

        실행되지 않는다.

        """
        ...
    
    def HwpCtrlFileSaveAutoBlock(self) -> bool:
        """
        한/글 컨트롤 전용 블록 저장.

        실행되지 않는다.

        """
        ...
    
    def HwpCtrlFindDlg(self) -> bool:
        """
        한/글 컨트롤 전용 찾기 대화상자.

        실행되지 않는다.

        """
        ...
    
    def HwpCtrlReplaceDlg(self) -> bool:
        """
        한/글 컨트롤 전용 바꾸기 대화상자

        """
        ...
    
    def HwpDic(self) -> bool:
        """
        한컴 사전(F12).

        현재 캐럿이 닿아 있거나, 블록선택한 구간을 검색어에 자동으로 넣는다.

        """
        ...
    
    def HwpTabViewAction(self) -> bool:
        """빠른 실행 작업창"""
        ...
    
    def HwpTabViewAttribute(self) -> bool:
        """양식 개체 속성 작업창"""
        ...
    
    def HwpTabViewClipboard(self) -> bool:
        """클립보드 작업창"""
        ...
    
    def HwpTabViewDistant(self) -> bool:
        """쪽모양 보기 작업창"""
        ...
    
    def HwpTabViewHwpDic(self) -> bool:
        """사전 검색 작업창"""
        ...
    
    def HwpTabViewMasterPage(self) -> bool:
        """바탕쪽 보기 작업창"""
        ...
    
    def HwpTabViewOutline(self) -> bool:
        """개요 보기 작업창"""
        ...
    
    def HwpTabViewScript(self) -> bool:
        """스크립트 작업창"""
        ...
    
    def HwpViewType(self) -> bool:
        """문서창 모양 설정"""
        ...
    
    def HwpWSDic(self) -> bool:
        """사전 검색 작업창 (Shift + F12)"""
        ...
    
    def HyperlinkBackward(self) -> bool:
        """
        하이퍼링크 뒤로.

        하이퍼링크를 통해서 문서를 탐색하여 페이지나 캐럿을 이동한 경우, (브라우저의 "뒤로가기"처럼) 이동 전의 위치로 돌아간다.

        """
        ...
    
    def HyperlinkForward(self) -> bool:
        """
        하이퍼링크 앞으로.

        ``hwp.HyperlinkBackward()`` 에 상반되는 명령어로, 브라우저의 "앞으로 가기"나 한/글의 재실행과 유사하다. 하이퍼링크 등으로 이동한 후에 뒤로가기를 눌렀다면, 캐럿이 뒤로가기 전 위치로 다시 이동한다.

        """
        ...
    
    def ImageFindPath(self) -> bool:
        """
        그림 경로 찾기.

        현재는 실행되지 않는 듯.

        """
        ...
    
    def InputCodeChange(self) -> bool:
        """
        문자/코드 변환

        현재 캐럿의 바로 앞 문자를 찾아서 문자이면 코드로, 코드이면 문자로 변환해준다.(변환 가능한 코드영역 0x0020 ~ 0x10FFFF 까지)

        """
        ...
    
    def InputHanja(self) -> bool:
        """
        한자로 바꾸기 창을 띄워준다.

        추가입력이 필요하여 자동화에는 쓰이지 않음.

        """
        ...
    
    def InputHanjaBusu(self) -> bool:
        """
        부수로 입력.

        자동화에는 쓰이지 않음.

        """
        ...
    
    def InputHanjaMean(self) -> bool:
        """
        한자 새김 입력창 띄우기.

        뜻과 음을 입력하면 적절한 한자를 삽입해준다.입력시 뜻과 음은 붙여서 입력. (예)하늘천

        """
        ...
    
    def InsertAutoNum(self) -> bool:
        """
        번호 다시 넣기(?)

        실행이 안되는 듯.

        """
        ...
    
    def InsertCpNo(self) -> bool:
        """
        현재 쪽번호(상용구) 삽입.

        쪽번호와 마찬가지로, 문자열이 실시간으로 변경된다.

        ※유의사항 : 이 쪽번호는 찾기, 찾아바꾸기, GetText 및 누름틀 안에 넣고 GetFieldText나 복붙 등 그 어떤 방법으로도 추출되지 않는다.
        한 마디로 눈에는 보이는 것 같지만 실재하지 않는 숫자임. 참고로 표번호도 그렇다. 값이 아니라 속성이라서 그렇다.

        """
        ...
    
    def InsertCpTpNo(self) -> bool:
        """
        상용구 코드 넣기(현재 쪽/전체 쪽).

        실시간으로 변경된다.

        """
        ...
    
    def InsertDateCode(self) -> bool:
        """
        상용구 코드 넣기(만든 날짜).

        현재날짜가 아님에 유의.

        """
        ...
    
    def InsertDocInfo(self) -> bool:
        """
        상용구 코드 넣기

        (만든 사람, 현재 쪽, 만든 날짜)

        """
        ...
    
    def InsertEndnote(self) -> bool:
        """
        미주 입력

        """
        ...
    
    def InsertFieldDateTime(self) -> bool:
        """
        날짜/시간 코드로 넣기([입력-날짜/시간-날짜/시간 코드]메뉴와 동일)

        """
        ...
    
    def InsertFieldMemo(self) -> bool:
        """
        메모 넣기([입력-메모-메모 넣기]메뉴와 동일)

        """
        ...
    
    def InsertFieldRevisionChagne(self) -> bool:
        """
        메모고침표 넣기

        (현재 한/글메뉴에 없음, 메모와 동일한 기능)

        """
        ...
    
    def InsertFixedWidthSpace(self) -> bool:
        """
        고정폭 빈칸 삽입

        """
        ...
    
    def InsertFootnote(self) -> bool:
        """
        각주 입력

        """
        ...
    
    def InsertLastPrintDate(self) -> bool:
        """
        상용구 코드 넣기(마지막 인쇄한 날짜)

        """
        ...
    
    def InsertLastSaveBy(self) -> bool:
        """
        상용구 코드 넣기(마지막 저장한 사람)

        """
        ...
    
    def InsertLastSaveDate(self) -> bool:
        """
        상용구 코드 넣기(마지막 저장한 날짜)

        """
        ...
    
    def InsertLine(self) -> bool:
        """
        선 넣기

        """
        ...
    
    def InsertNonBreakingSpace(self) -> bool:
        """
        묶음 빈칸 삽입

        """
        ...
    
    def InsertPageNum(self) -> bool:
        """
        쪽 번호 넣기

        """
        ...
    
    def InsertSoftHyphen(self) -> bool:
        """
        하이픈 삽입

        """
        ...
    
    def InsertSpace(self) -> bool:
        """
        공백 삽입

        """
        ...
    
    def InsertStringDateTime(self) -> bool:
        """
        날짜/시간 넣기 - 문자열로 넣기([입력-날짜/시간-날짜/시간 문자열]메뉴와 동일)

        """
        ...
    
    def InsertTab(self) -> bool:
        """
        탭 삽입

        """
        ...
    
    def InsertTpNo(self) -> bool:
        """
        상용구 코드 넣기(전체 쪽수)

        """
        ...
    
    def Jajun(self) -> bool:
        """
        한자 자전

        """
        ...
    
    def LabelAdd(self) -> bool:
        """
        라벨 새 쪽 추가하기

        """
        ...
    
    def LabelTemplate(self) -> bool:
        """
        라벨 문서 만들기

        """
        ...
    
    def LeftShiftBlock(self) -> bool:
        """텍스트 블록 상태에서 블록 왼쪽에 있는 탭 또는 공백을 지운다."""
        ...
    
    def LeftTabFrameClose(self) -> bool:
        """왼쪽 작업창 감추기"""
        ...
    
    def LinkTextBox(self) -> bool:
        """
        글상자 연결.

        글상자가 선택되지 않았거나, 캐럿이 글상자 내부에 있지 않으면 동작하지 않는다.

        """
        ...
    
    def MacroPause(self) -> bool:
        """
        매크로 실행 일시 중지 (정의/실행)

        """
        ...
    
    def MacroPlay1(self) -> bool:
        """
        매크로 1

        """
        ...
    
    def MacroPlay2(self) -> bool:
        """
        매크로 2

        """
        ...
    
    def MacroPlay3(self) -> bool:
        """
        매크로 3

        """
        ...
    
    def MacroPlay4(self) -> bool:
        """
        매크로 4

        """
        ...
    
    def MacroPlay5(self) -> bool:
        """
        매크로 5

        """
        ...
    
    def MacroPlay6(self) -> bool:
        """
        매크로 6

        """
        ...
    
    def MacroPlay7(self) -> bool:
        """
        매크로 7

        """
        ...
    
    def MacroPlay8(self) -> bool:
        """
        매크로 8

        """
        ...
    
    def MacroPlay9(self) -> bool:
        """
        매크로 9

        """
        ...
    
    def MacroPlay10(self) -> bool:
        """
        매크로 10

        """
        ...
    
    def MacroPlay11(self) -> bool:
        """
        매크로 11

        """
        ...
    
    def MacroRepeat(self) -> bool:
        """
        매크로 실행

        """
        ...
    
    def MacroStop(self) -> bool:
        """
        매크로 실행 중지 (정의/실행)

        """
        ...
    
    def MailMergeField(self) -> bool:
        """
        메일 머지 필드(표시달기 or 고치기)

        """
        ...
    
    def MakeIndex(self) -> bool:
        """
        찾아보기 만들기

        """
        ...
    
    def ManualChangeHangul(self) -> bool:
        """
        한영 수동 전환

        현재 커서위치 또는 문단나누기 이전에 입력된 내용에 대해서 강제적으로 한/영 전환을 한다.

        """
        ...
    
    def MarkPenColor(self) -> bool:
        """형광펜 색"""
        ...
    
    def MarkPenNext(self) -> bool:
        """
        다음 형광펜 삽입 위치로 이동한다.
        """
        ...
    
    def MarkPenPrev(self) -> bool:
        """
        이전 형광펜 삽입 위치로 이동한다.
        """
        ...
    
    def MetatagExist(self, tag): # -> Any:
        """특정 이름의 메타태그가 존재하는지?"""
        ...
    
    def MarkTitle(self) -> bool:
        """
        제목 차례 표시([도구-차례/찾아보기-제목 차례 표시]메뉴에 대응).

        차례 코드가 삽입되어 나중에 차례 만들기에서 사용할 수 있다.
        적용여부는 Ctrl+G,C를 이용해 조판부호를 확인하면 알 수 있다.

        """
        ...
    
    def MasterPage(self) -> bool:
        """
        바탕쪽 진입

        """
        ...
    
    def MasterPageDuplicate(self) -> bool:
        """
        기존 바탕쪽과 겹침.

        바탕쪽 편집상태가 활성화되어 있으며 [구역 마지막쪽], [구역임의 쪽]일 경우에만 사용 가능하다.

        """
        ...
    
    def MasterPageExcept(self) -> bool:
        """
        첫 쪽 제외

        """
        ...
    
    def MasterPageFront(self) -> bool:
        """
        바탕쪽 앞으로 보내기.

        바탕쪽 편집모드일 경우에만 동작한다.

        """
        ...
    
    def MasterPagePrevSection(self) -> bool:
        """
        앞 구역 바탕쪽 사용

        """
        ...
    
    def MasterPageToNext(self) -> bool:
        """
        이후 바탕쪽

        """
        ...
    
    def MasterPageToPrevious(self) -> bool:
        """
        이전 바탕쪽

        """
        ...
    
    def MasterPageType(self) -> bool:
        """바탕쪽 종류"""
        ...
    
    def MasterWsItemOnOff(self) -> bool:
        """바탕쪽 작업창 보이기/감추기"""
        ...
    
    def ModifyComposeChars(self) -> bool:
        """
        고치기 - 글자 겹침

        """
        ...
    
    def ModifyCtrl(self) -> bool:
        """
        고치기 : 컨트롤

        """
        ...
    
    def ModifyDutmal(self) -> bool:
        """
        고치기 - 덧말

        """
        ...
    
    def ModifyFillProperty(self) -> bool:
        """
        고치기(채우기 속성 탭으로).

        만약 Ctrl(ShapeObject,누름틀, 날짜/시간 코드 등)이 선택되지 않았다면 역방향탐색(SelectCtrlReverse)을 이용해서 개체를 탐색한다.
        채우기 속성이 없는 Ctrl일 경우에는 첫 번째 탭이 선택된 상태로 고치기 창이 뜬다.

        """
        ...
    
    def ModifyLineProperty(self) -> bool:
        """
        고치기(선/테두리 속성 탭으로).

        만약 Ctrl(ShapeObject,누름틀, 날짜/시간 코드 등)이 선택되지 않았다면 역방향탐색(SelectCtrlReverse)을 이용해서 개체를 탐색한다.
        선/테두리 속성이 없는 Ctrl일 경우에는 첫 번째 탭이 선택된 상태로 고치기 창이 뜬다.

        """
        ...
    
    def ModifyShapeObject(self) -> bool:
        """
        고치기 - 개체 속성

        """
        ...
    
    def MoveColumnBegin(self) -> bool:
        """
        단의 시작점으로 이동

        단이 없을 경우에는 아무동작도 하지 않는다. 해당 리스트 안에서만 동작한다.

        """
        ...
    
    def MoveColumnEnd(self) -> bool:
        """
        단의 끝점으로 이동한다.

        단이 없을 경우에는 아무동작도 하지 않는다. 해당 리스트 안에서만 동작한다.

        """
        ...
    
    def MoveDocBegin(self) -> bool:
        """
        문서의 시작으로 이동

        만약 셀렉션을 확장하는 경우에는 LIST_BEGIN/END와 동일하다.
        현재 서브 리스트 내에 있으면 빠져나간다. 자동화에 아주 많이 사용된다.

        """
        ...
    
    def MoveDocEnd(self) -> bool:
        """
        문서의 끝으로 이동

        만약 셀렉션을 확장하는 경우에는 LIST_BEGIN/END와 동일하다.
        현재 서브 리스트 내에 있으면 빠져나간다.

        """
        ...
    
    def PutParaNumber(self) -> bool:
        """
        문단번호 삽입/제거 토글

        """
        ...
    
    def PutOutlinleNumber(self) -> bool:
        """
        개요번호 삽입/제거 토글

        """
        ...
    
    def Close(self) -> bool:
        """
        현재 리스트를 닫고 (최)상위 리스트로 이동하는 액션.

        대표적인 예로, 메모나 각주 등을 작성한 후 본문으로 빠져나올 때, 혹은 여러 겹의 표 안에 있을 때 한 번에 표 밖으로 캐럿을 옮길 때 사용한다. 굉장히 자주 쓰이는 액션이며, 경우에 따라 Close가 아니라 CloseEx를 써야 하는 경우도 있다.
        (레퍼런스 포인트가 등록되어 있으면 그 포인트로, 없으면 루트 리스트로 이동한다. 나머지 특성은 MoveRootList와 동일)
        """
        ...
    
    def DeleteDocumentMasterPage(self): # -> Any:
        """
        문서의 마스터페이지 삭제하기
        """
        ...
    
    def DeleteSectionMasterPage(self): # -> Any:
        """
        섹션의 마스터페이지 삭제하기
        """
        ...
    
    def UnSelectCtrl(self): # -> Any:
        """선택중인 컨트롤 선택해제"""
        ...
    
    def WindowAlignCascade(self): # -> Any:
        """창 겹치게 배열"""
        ...
    
    def WindowAlignTileHorz(self): # -> Any:
        """창 가로로 배열"""
        ...
    
    def WindowAlignTileVert(self): # -> Any:
        """창 세로로 배열"""
        ...
    
    def WindowList(self): # -> Any:
        """창 목록"""
        ...
    
    def WindowMinimizeAll(self): # -> Any:
        """창 모두 아이콘으로 배열"""
        ...
    
    def WindowNextPane(self): # -> Any:
        """다음 분할창 활성화"""
        ...
    
    def WindowNextTab(self): # -> Any:
        """다음 창 활성화"""
        ...
    
    def WindowPrevTab(self): # -> Any:
        """이전 창 활성화"""
        ...
    
    def Cut(self, remove_cell=...) -> bool:
        """
        잘라내기.

        Copy 액션과 유사하지만,
        복사 대신 잘라내기 기능을 수행한다.
        유용하지만, 빠른 반복작업에서는 윈도우OS의 클립보드 잠금 때문에 오류가 발생할 수 있다.

        """
        ...
    
    def Delete(self, delete_ctrl: bool = ...) -> bool:
        """
        삭제(Del키).

        키보드의 Del 키를 눌렀을 때와 거의(?) 유사하다.
        아주 사용빈도가 높은 액션이다.
        수작업과 달리 표나 이미지 등의 컨트롤을 삭제할 때에도 팝업으로 묻지 않는다.
        (``hwp.Delete(False)``로 실행하면 경고팝업이 뜬다.)

        Args:
            delete_ctrl: 컨트롤(표, 이미지, 겹침문자 등)을 삭제할 때 처리방법(True: 삭제(기본값), False: 삭제안함)

        Returns:
            성공시 True, 실패시 False를 리턴
        """
        ...
    
    def DeleteBack(self, delete_ctrl: bool = ...) -> bool:
        """
        백스페이스 삭제

        Delete와 유사하지만, 이건 Backspace처럼 우측에서 좌측으로 삭제해준다. 많이 쓰인다.

        Args:
            delete_ctrl: 컨트롤 삭제시 경고팝업을 띄울지(기본값은 True)

        """
        ...
    
    def DeleteLine(self, delete_ctrl=...): # -> Any:
        """
        한 줄 지우기(Ctrl-Y) 액션.

        문단나눔과 전혀 상관없이 딱 한 줄의 텍스트가 삭제된다.
        원래 액션과 달리 DeleteLine으로 표 등의 객체를 삭제하는 경우에
        경고팝업이 뜨지 않으므로 유의해야 한다.
        만약 컨트롤을 지우고 싶지 않다면 인수에 False를 넣으면 된다.

        """
        ...
    
    def DeleteLineEnd(self, delete_ctrl=...): # -> Any:
        """
        현재 커서에서 줄 끝까지 지우기(Alt-Y).

        수작업시에 굉장히 유용한 기능일 수 있지만,
        자동화 작업시에는 DeleteLine이나 DeleteLineEnd 모두,
        한 줄 안에 어떤 내용까지 있는지 파악하기 어려운 관계로,
        자동화에 잘 쓰이지는 않는다.
        원래 액션과 달리 DeleteLineEnd로 표 등의 객체를 삭제하는 경우에
        경고팝업이 뜨지 않으므로 유의해야 한다.
        만약 컨트롤을 지우고 싶지 않다면 인수에 False를 넣으면 된다.
        """
        ...
    
    def DeleteWord(self, delete_ctrl=...): # -> Any:
        """
        단어 지우기(Ctrl-T) 액션.

        단, 커서 우측에 위치한 단어 한 개씩 삭제하며, 커서가 단어 중간에 있는 경우 우측 글자만 삭제한다.

        """
        ...
    
    def DeleteWordBack(self, delete_ctrl=...): # -> Any:
        """
        한 단어씩 좌측으로 삭제하는 액션(Ctrl-백스페이스).

        DeleteWord와 마찬가지로 커서가 단어 중간에 있는 경우
        좌측 글자만 삭제한다.

        """
        ...
    
    def MoveDown(self): # -> bool:
        """
        캐럿을 (논리적 개념의) 아래로 이동시킨다.

        """
        ...
    
    def MoveLeft(self): # -> bool:
        """
        캐럿을 (논리적 개념의) 왼쪽으로 이동시킨다.

        """
        ...
    
    def MoveLineBegin(self): # -> Any:
        """
        현재 위치한 줄의 시작/끝으로 이동

        """
        ...
    
    def MoveLineDown(self): # -> Any:
        """
        한 줄 아래로 이동한다.

        """
        ...
    
    def MoveLineEnd(self): # -> bool:
        """
        현재 위치한 줄의 시작/끝으로 이동

        """
        ...
    
    def MoveLineUp(self): # -> bool:
        """
        한 줄 위로 이동한다.

        """
        ...
    
    def MoveListBegin(self): # -> Any:
        """
        현재 리스트의 시작으로 이동

        """
        ...
    
    def MoveListEnd(self): # -> Any:
        """
        현재 리스트의 끝으로 이동

        """
        ...
    
    def MoveNextChar(self): # -> bool:
        """
        한 글자 뒤로 이동.

        현재 리스트만을 대상으로 동작한다.

        """
        ...
    
    def MoveNextColumn(self): # -> bool:
        """
        뒤 단으로 이동

        """
        ...
    
    def MoveNextParaBegin(self): # -> bool:
        """
        앞 문단의 끝/다음 문단의 시작으로 이동.

        현재 리스트만을 대상으로 동작한다.

        """
        ...
    
    def MoveNextPos(self): # -> bool:
        """
        한 글자 뒤로 이동.

        서브 리스트를 옮겨 다닐 수 있다.

        """
        ...
    
    def MoveNextPosEx(self): # -> bool:
        """
        한 글자 뒤로 이동. 서브 리스트를 옮겨 다닐 수 있다.

        (머리말, 꼬리말, 각주, 미주, 글상자 포함)
        예를 들어, 문단 중간에 글상자가 (글자처럼취급 꺼진상태로) 떠있다면
        MoveNextPos는 글상자를 패스하고 본문만 통과해서 지나가는데,
        MoveNextPosEx는 캐럿이 컨트롤을 만나는 시점에 글상자 안으로 들어갔다 나온다.
        문서 전체를 훑어야 하는 경우에는 굉장히 유용하게 쓰일 듯.
        """
        ...
    
    def MoveNextWord(self): # -> bool:
        """
        한 단어 뒤로 이동.

        현재 리스트만을 대상으로 동작한다.

        """
        ...
    
    def MovePageBegin(self): # -> Any:
        """
        현재 페이지의 시작점으로 이동한다.

        만약 캐럿의 위치가 변경되었다면 화면이 전환되어 쪽의 상단으로 페이지뷰잉이 맞춰진다.

        """
        ...
    
    def MovePageDown(self): # -> bool:
        """
        앞 페이지의 시작으로 이동.

        현재 탑레벨 리스트가 아니면 탑레벨 리스트로 빠져나온다.

        """
        ...
    
    def MovePageEnd(self): # -> bool:
        """
        현재 페이지의 끝점으로 이동한다.

        만약 캐럿의 위치가 변경되었다면 화면이 전환되어 쪽의 하단으로 페이지뷰잉이 맞춰진다.

        """
        ...
    
    def MovePageUp(self): # -> bool:
        """
        뒤 페이지의 시작으로 이동.

        현재 탑레벨 리스트가 아니면 탑레벨 리스트로 빠져나온다.

        """
        ...
    
    def MoveParaBegin(self): # -> Any:
        """
        현재 위치한 문단의 시작/끝으로 이동

        """
        ...
    
    def MoveParaEnd(self): # -> Any:
        """
        현재 위치한 문단의 시작/끝으로 이동

        """
        ...
    
    def MoveParentList(self): # -> Any:
        """
        한 레벨 상위/탑레벨/루트 리스트로 이동한다

        현재 루트 리스트에 위치해 있어 더 이상 상위 리스트가 없을 때는 위치 이동 없이 리턴한다.
        이동한 후의 위치는 상위 리스트에서 서브리스트가 속한 컨트롤 코드가 위치한 곳이다.
        위치 이동시 셀렉션은 무조건 풀린다.

        """
        ...
    
    def MovePrevChar(self): # -> bool:
        """
        한 글자 앞 이동.

        현재 리스트만을 대상으로 동작한다.

        """
        ...
    
    def MovePrevColumn(self): # -> bool:
        """
        앞 단으로 이동

        """
        ...
    
    def MovePrevParaBegin(self): # -> bool:
        """
        앞 문단의 시작으로 이동.

        현재 리스트만을 대상으로 동작한다.

        """
        ...
    
    def MovePrevParaEnd(self): # -> bool:
        """
        앞 문단의 끝으로 이동.

        현재 리스트만을 대상으로 동작한다.

        """
        ...
    
    def MovePrevPos(self): # -> bool:
        """
        한 글자 앞으로 이동.

        서브 리스트를 옮겨 다닐 수 있다.

        """
        ...
    
    def MovePrevPosEx(self): # -> bool:
        """
        한 글자 앞으로 이동.

        서브 리스트를 옮겨 다닐 수 있다.
        (머리말, 꼬리말, 각주, 미주, 글상자 포함)
        """
        ...
    
    def MovePrevWord(self): # -> bool:
        """
        한 단어 앞으로 이동.

        현재 리스트만을 대상으로 동작한다.

        """
        ...
    
    def MoveRight(self): # -> bool:
        """
        캐럿을 (논리적 개념의) 오른쪽으로 이동시킨다.

        """
        ...
    
    def MoveRootList(self): # -> Any:
        """
        한 레벨 상위/탑레벨/루트 리스트로 이동한다

        현재 루트 리스트에 위치해 있어 더 이상 상위 리스트가 없을 때는 위치 이동 없이 리턴한다.
        이동한 후의 위치는 상위 리스트에서 서브리스트가 속한 컨트롤 코드가 위치한 곳이다.
        위치 이동시 셀렉션은 무조건 풀린다.

        """
        ...
    
    def MoveScrollDown(self): # -> Any:
        """
        아래 방향으로 스크롤하면서 이동

        """
        ...
    
    def MoveScrollNext(self): # -> Any:
        """
        다음 방향으로 스크롤하면서 이동

        """
        ...
    
    def MoveScrollPrev(self): # -> Any:
        """
        이전 방향으로 스크롤하면서 이동

        """
        ...
    
    def MoveScrollUp(self): # -> Any:
        """
        위 방향으로 스크롤하면서 이동

        """
        ...
    
    def MoveSectionDown(self): # -> bool:
        """
        뒤 섹션으로 이동.

        현재 루트 리스트가 아니면 루트 리스트로 빠져나온다.

        """
        ...
    
    def MoveSectionUp(self): # -> bool:
        """
        앞 섹션으로 이동.

        현재 루트 리스트가 아니면 루트 리스트로 빠져나온다.

        """
        ...
    
    def MoveSelDocBegin(self): # -> Any:
        """
        선택 상태로 문서 처음으로 이동

        """
        ...
    
    def MoveSelDocEnd(self): # -> Any:
        """
        선택 상태로 문서 끝으로 이동

        """
        ...
    
    def MoveSelDown(self): # -> bool:
        """
        선택 상태로 캐럿을 (논리적 방향) 아래로 이동

        """
        ...
    
    def MoveSelLeft(self): # -> bool:
        """
        선택 상태로 캐럿을 (논리적 방향) 왼쪽으로 이동

        """
        ...
    
    def MoveSelLineBegin(self): # -> Any:
        """
        선택 상태로 줄 처음으로 이동

        """
        ...
    
    def MoveSelLineDown(self): # -> bool:
        """
        선택 상태로 한줄 아래로 이동

        """
        ...
    
    def MoveSelLineEnd(self): # -> Any:
        """
        선택 상태로 줄 끝으로 이동

        """
        ...
    
    def MoveSelLineUp(self): # -> bool:
        """
        선택 상태로 한줄 위로 이동

        """
        ...
    
    def MoveSelListBegin(self): # -> Any:
        """
        선택 상태로 리스트 처음으로 이동

        """
        ...
    
    def MoveSelListEnd(self): # -> Any:
        """
        선택 상태로 리스트 끝으로 이동

        """
        ...
    
    def MoveSelNextChar(self): # -> bool:
        """
        선택 상태로 다음 글자로 이동

        """
        ...
    
    def MoveSelNextParaBegin(self): # -> bool:
        """
        선택 상태로 다음 문단 처음으로 이동

        """
        ...
    
    def MoveSelNextPos(self): # -> bool:
        """
        선택 상태로 다음 커서위치(글자)로 이동

        """
        ...
    
    def MoveSelNextWord(self): # -> bool:
        """
        선택 상태로 다음 단어로 이동

        """
        ...
    
    def MoveSelPageDown(self): # -> bool:
        """
        선택 상태로 PageDown 이동

        """
        ...
    
    def MoveSelPageUp(self): # -> bool:
        """
        선택 상태로 PageUp 이동

        """
        ...
    
    def MoveSelParaBegin(self): # -> Any:
        """
        선택 상태로 문단 처음으로 이동

        """
        ...
    
    def MoveSelParaEnd(self): # -> Any:
        """
        선택 상태로 문단 끝으로 이동

        """
        ...
    
    def MoveSelPrevChar(self): # -> bool:
        """
        선택 상태로 이전 글자로 이동

        """
        ...
    
    def MoveSelPrevParaBegin(self): # -> bool:
        """
        선택 상태로 이전 문단 시작으로 이동

        """
        ...
    
    def MoveSelPrevParaEnd(self): # -> bool:
        """
        선택 상태로 이전 문단 끝으로 이동

        """
        ...
    
    def MoveSelPrevPos(self): # -> bool:
        """
        선택 상태로 이전 위치(글자)로 이동

        """
        ...
    
    def MoveSelPrevWord(self): # -> bool:
        """
        선택 상태로 이전 단어로 이동

        """
        ...
    
    def MoveSelRight(self): # -> bool:
        """
        선택 상태로 캐럿을 (논리적 방향) 오른쪽으로 이동

        """
        ...
    
    def MoveSelTopLevelBegin(self): # -> Any:
        """
        선택 상태로 문서의 탑레벨 처음으로 이동(==``hwp.MoveDocBegin()``)

        """
        ...
    
    def MoveSelTopLevelEnd(self): # -> Any:
        """
        선택 상태로 탑레벨 끝으로 이동

        """
        ...
    
    def MoveSelUp(self): # -> bool:
        """
        선택 상태로 캐럿을 (논리적 방향) 위로 이동

        """
        ...
    
    def MoveSelViewDown(self): # -> bool:
        """
        선택 상태로 화면 시점의 아래로 이동

        Shift-PgDn 기능과 동일

        """
        ...
    
    def MoveSelViewUp(self): # -> bool:
        """
        선택 상태로 화면 시점의 위로 이동

        Shift-PgUp 기능과 동일

        """
        ...
    
    def MoveSelWordBegin(self): # -> Any:
        """
        선택 상태로 단어 처음으로 이동

        """
        ...
    
    def MoveSelWordEnd(self): # -> Any:
        """
        선택 상태로 단어 끝으로 이동

        """
        ...
    
    def MoveTopLevelBegin(self): # -> Any:
        """
        탑레벨 리스트의 시작으로 이동

        """
        ...
    
    def MoveTopLevelEnd(self): # -> Any:
        """
        탑레벨 리스트의 끝으로 이동

        """
        ...
    
    def MoveTopLevelList(self): # -> Any:
        """
        한 레벨 상위/탑레벨/루트 리스트로 이동

        현재 루트 리스트에 위치해 있어 더 이상 상위 리스트가 없을 때는 위치 이동 없이 리턴한다.
        이동한 후의 위치는 상위 리스트에서 서브리스트가 속한 컨트롤 코드가 위치한 곳이다.
        위치 이동시 셀렉션은 무조건 풀린다.

        """
        ...
    
    def MoveUp(self): # -> bool:
        """
        캐럿을 (논리적 개념의) 위로 이동시킨다.

        """
        ...
    
    def MoveViewBegin(self): # -> Any:
        """
        현재 뷰의 시작에 위치한 곳으로 이동

        """
        ...
    
    def MoveViewDown(self): # -> bool:
        """
        현재 뷰의 크기만큼 아래로 이동한다. PgDn 키의 기능이다.

        """
        ...
    
    def MoveViewEnd(self): # -> Any:
        """
        현재 뷰의 끝에 위치한 곳으로 이동

        """
        ...
    
    def MoveViewUp(self): # -> bool:
        """
        현재 뷰의 크기만큼 위로 이동한다. PgUp 키의 기능이다.

        """
        ...
    
    def MoveWordBegin(self): # -> Any:
        """
        현재 위치한 단어의 시작으로 이동. 현재 리스트만을 대상으로 동작한다.

        """
        ...
    
    def MoveWordEnd(self): # -> Any:
        """
        현재 위치한 단어의 끝으로 이동. 현재 리스트만을 대상으로 동작한다.

        """
        ...
    
    def MPSectionToNext(self): # -> Any:
        """
        이후 구역으로

        """
        ...
    
    def MPSectionToPrevious(self): # -> Any:
        """
        이전 구역으로

        """
        ...
    
    def NextTextBoxLinked(self): # -> Any:
        """
        연결된 글상자의 다음 글상자로 이동

        """
        ...
    
    def NoteDelete(self): # -> Any:
        """
        주석 지우기

        """
        ...
    
    def NoSplit(self): # -> Any:
        """창 나누지 않음"""
        ...
    
    def NoteLineColor(self): # -> Any:
        """주석 구분선 색"""
        ...
    
    def NoteLineLength(self): # -> Any:
        """주석 구분선 길이"""
        ...
    
    def NoteLineShape(self): # -> Any:
        """주석 구분선 모양"""
        ...
    
    def NoteLineWeight(self): # -> Any:
        """주석 구분선 굵기"""
        ...
    
    def NoteModify(self): # -> Any:
        """
        주석 고치기

        """
        ...
    
    def NoteNumProperty(self): # -> Any:
        """
        주석 번호 속성

        """
        ...
    
    def NoteNumShape(self): # -> Any:
        """주석 번호 모양"""
        ...
    
    def NotePosition(self): # -> Any:
        """각주 위치"""
        ...
    
    def NoteToNext(self): # -> Any:
        """
        주석 다음으로 이동

        """
        ...
    
    def NoteToPrev(self): # -> Any:
        """
        주석 앞으로 이동

        """
        ...
    
    def ParagraphShapeAlignCenter(self): # -> Any:
        """
        가운데 정렬

        """
        ...
    
    def ParagraphShapeAlignDistribute(self): # -> Any:
        """
        배분 정렬

        """
        ...
    
    def ParagraphShapeAlignDivision(self): # -> Any:
        """
        나눔 정렬

        """
        ...
    
    def ParagraphShapeAlignJustify(self): # -> Any:
        """
        양쪽 정렬

        """
        ...
    
    def ParagraphShapeAlignLeft(self): # -> Any:
        """
        왼쪽 정렬

        """
        ...
    
    def ParagraphShapeAlignRight(self): # -> Any:
        """
        오른쪽 정렬

        """
        ...
    
    def ParagraphShapeDecreaseLeftMargin(self): # -> Any:
        """
        왼쪽 여백 줄이기

        """
        ...
    
    def ParagraphShapeDecreaseLineSpacing(self): # -> Any:
        """
        줄 간격을 점점 좁힘

        """
        ...
    
    def ParagraphShapeDecreaseMargin(self): # -> Any:
        """
        왼쪽-오른쪽 여백 줄이기

        """
        ...
    
    def ParagraphShapeDecreaseRightMargin(self): # -> Any:
        """
        오른쪽 여백 키우기

        """
        ...
    
    def ParagraphShapeIncreaseLeftMargin(self): # -> Any:
        """
        왼쪽 여백 키우기

        """
        ...
    
    def ParagraphShapeIncreaseLineSpacing(self): # -> Any:
        """
        줄 간격을 점점 넓힘

        """
        ...
    
    def ParagraphShapeIncreaseMargin(self): # -> Any:
        """
        왼쪽-오른쪽 여백 키우기

        """
        ...
    
    def ParagraphShapeIncreaseRightMargin(self): # -> Any:
        """
        오른쪽 여백 줄이기

        """
        ...
    
    def ParagraphShapeIndentAtCaret(self): # -> Any:
        """
        첫 줄 내어 쓰기

        """
        ...
    
    def ParagraphShapeIndentNegative(self): # -> Any:
        """
        첫 줄을 한 글자 내어 씀

        """
        ...
    
    def ParagraphShapeIndentPositive(self): # -> Any:
        """
        첫 줄을 한 글자 들여 씀

        """
        ...
    
    def ParagraphShapeProtect(self): # -> Any:
        """
        문단 보호

        """
        ...
    
    def ParagraphShapeWithNext(self): # -> Any:
        """
        다음 문단과 함께

        """
        ...
    
    def ParaShapeLineSpace(self): # -> Any:
        """문단 모양"""
        ...
    
    def Paste(self): # -> Any:
        """
        일반 붙이기(Ctrl-V)

        확장 붙여넣기는 hwp.paste() 사용.
        """
        ...
    
    def PastePage(self): # -> Any:
        """
        쪽 붙여넣기

        한글2014 이하의 버전에서는 작동하지 않는다.

        """
        ...
    
    def PasteSpecial(self): # -> Any:
        """
        골라 붙이기

        """
        ...
    
    def PictureEffect1(self): # -> Any:
        """
        그림 그레이 스케일

        """
        ...
    
    def PictureEffect2(self): # -> Any:
        """
        그림 흑백으로

        """
        ...
    
    def PictureEffect3(self): # -> Any:
        """
        그림 워터마크

        """
        ...
    
    def PictureEffect4(self): # -> Any:
        """
        그림 효과 없음

        """
        ...
    
    def PictureEffect5(self): # -> Any:
        """
        그림 밝기 증가

        """
        ...
    
    def PictureEffect6(self): # -> Any:
        """
        그림 밝기 감소

        """
        ...
    
    def PictureEffect7(self): # -> Any:
        """
        그림 명암 증가

        """
        ...
    
    def PictureEffect8(self): # -> Any:
        """
        그림 명암 감소

        """
        ...
    
    def PictureInsertDialog(self): # -> Any:
        """
        그림 넣기 대화상자

        (대화상자를 띄워 선택한 이미지 파일을 문서에 삽입하는 액션 : API용)

        """
        ...
    
    def PictureLinkedToEmbedded(self): # -> Any:
        """
        연결된 그림을 모두 삽입그림으로

        """
        ...
    
    def PictureSave(self): # -> Any:
        """
        그림 빼내기

        """
        ...
    
    def PictureScissor(self): # -> Any:
        """
        그림 자르기

        """
        ...
    
    def PictureToOriginal(self): # -> Any:
        """
        그림을 원래 그림으로

        """
        ...
    
    def PrevTextBoxLinked(self): # -> Any:
        """
        연결된 글상자의 이전 글상자로 이동.

        현재 글상자가 선택되거나, 글상자 내부에 캐럿이 존재하지 않으면 동작하지 않는다.

        """
        ...
    
    def PstAutoPlay(self): # -> Any:
        """프리젠테이션 자동 시연"""
        ...
    
    def PstBlackToWhite(self): # -> Any:
        """프리젠테이션 검은색 글자를 흰색으로 변경"""
        ...
    
    def PstGradientType(self): # -> Any:
        """프리젠테이션 그라데이션 형태"""
        ...
    
    def PstScrChangeType(self): # -> Any:
        """프리젠테이션 화면 전환 형태"""
        ...
    
    def PstSetupNextSec(self): # -> Any:
        """프리젠테이션 뒤 구역 설정"""
        ...
    
    def PstSetupPrevSec(self): # -> Any:
        """프리젠테이션 앞 구역 설정"""
        ...
    
    def QuickCommandRun(self): # -> Any:
        """
        입력 자동 명령 동작

        """
        ...
    
    def QuickCorrect(self): # -> Any:
        """
        빠른 교정 (실질적인 동작 Action)

        """
        ...
    
    def QuickCorrectRun(self): # -> Any:
        """
        빠른 교정 ― 내용 편집

        """
        ...
    
    def QuickCorrectSound(self): # -> Any:
        """
        빠른 교정 ― 메뉴에서 효과음 On/Off

        """
        ...
    
    def QuickMarkInsert0(self): # -> Any:
        """
        쉬운 책갈피0 - 삽입

        """
        ...
    
    def QuickMarkInsert1(self): # -> Any:
        """
        쉬운 책갈피1 - 삽입

        """
        ...
    
    def QuickMarkInsert2(self): # -> Any:
        """
        쉬운 책갈피2 - 삽입

        """
        ...
    
    def QuickMarkInsert3(self): # -> Any:
        """
        쉬운 책갈피3 - 삽입

        """
        ...
    
    def QuickMarkInsert4(self): # -> Any:
        """
        쉬운 책갈피4 - 삽입

        """
        ...
    
    def QuickMarkInsert5(self): # -> Any:
        """
        쉬운 책갈피5 - 삽입

        """
        ...
    
    def QuickMarkInsert6(self): # -> Any:
        """
        쉬운 책갈피6 - 삽입

        """
        ...
    
    def QuickMarkInsert7(self): # -> Any:
        """
        쉬운 책갈피7 - 삽입

        """
        ...
    
    def QuickMarkInsert8(self): # -> Any:
        """
        쉬운 책갈피8 - 삽입

        """
        ...
    
    def QuickMarkInsert9(self): # -> Any:
        """
        쉬운 책갈피9 - 삽입

        """
        ...
    
    def QuickMarkMove0(self): # -> Any:
        """
        쉬운 책갈피0 - 이동

        """
        ...
    
    def QuickMarkMove1(self): # -> Any:
        """
        쉬운 책갈피1 - 이동

        """
        ...
    
    def QuickMarkMove2(self): # -> Any:
        """
        쉬운 책갈피2 - 이동

        """
        ...
    
    def QuickMarkMove3(self): # -> Any:
        """
        쉬운 책갈피3 - 이동

        """
        ...
    
    def QuickMarkMove4(self): # -> Any:
        """
        쉬운 책갈피4 - 이동

        """
        ...
    
    def QuickMarkMove5(self): # -> Any:
        """
        쉬운 책갈피5 - 이동

        """
        ...
    
    def QuickMarkMove6(self): # -> Any:
        """
        쉬운 책갈피6 - 이동

        """
        ...
    
    def QuickMarkMove7(self): # -> Any:
        """
        쉬운 책갈피7 - 이동

        """
        ...
    
    def QuickMarkMove8(self): # -> Any:
        """
        쉬운 책갈피8 - 이동

        """
        ...
    
    def QuickMarkMove9(self): # -> Any:
        """
        쉬운 책갈피9 - 이동

        """
        ...
    
    def RecalcPageCount(self): # -> Any:
        """
        현재 페이지의 쪽 번호 재계산

        """
        ...
    
    def RecentCode(self): # -> Any:
        """
        최근에 사용한 문자표 입력.

        최근에 사용한 문자표가 없을 경우에는 문자표 대화상자를 띄운다.

        """
        ...
    
    def RecentEmpty(self): # -> Any:
        """최근 목록 지우기"""
        ...
    
    def RecentNoExistDel(self): # -> Any:
        """최근 목록에서 존재하지 않는 아이템 지우기"""
        ...
    
    def Redo(self): # -> Any:
        """
        다시 실행

        """
        ...
    
    def returnKeyInField(self): # -> Any:
        """
        캐럿이 필드 안에 위치한 상태에서 return Key에 대한 액션 분기

        첫 글자 r은 오타인 것으로 추정.

        """
        ...
    
    def ReturnKeyInField(self): # -> Any:
        """
        캐럿이 필드 안에 위치한 상태에서 return Key에 대한 액션 분기

        """
        ...
    
    def returnPrevPos(self): # -> Any:
        """
        직전위치로 돌아가기

        첫 글자 r은 오타인 것으로 추정.

        """
        ...
    
    def ReturnPrevPos(self): # -> Any:
        """
        직전위치로 돌아가기
        """
        ...
    
    def RightShiftBlock(self): # -> Any:
        """텍스트 블록 상태에서 블록이 문단의 시작위치에서 시작할 경우 블록 왼쪽에 탭을 삽입한다."""
        ...
    
    def RightTabFrameClose(self): # -> Any:
        """오른쪽 작업창 감추기"""
        ...
    
    def RunUserKeyLayout(self): # -> Any:
        """사용자 글자판 제작 툴"""
        ...
    
    def ScrMacroPause(self): # -> Any:
        """
        매크로 기록 일시정지/재시작

        """
        ...
    
    def ScrMacroPlay1(self): # -> Any:
        """
        1번 매크로 실행(Alt+Shift+#)

        """
        ...
    
    def ScrMacroPlay2(self): # -> Any:
        """
        2번 매크로 실행(Alt+Shift+#)

        """
        ...
    
    def ScrMacroPlay3(self): # -> Any:
        """
        3#번 매크로 실행(Alt+Shift+#)

        """
        ...
    
    def ScrMacroPlay4(self): # -> Any:
        """
        4번 매크로 실행(Alt+Shift+#)

        """
        ...
    
    def ScrMacroPlay5(self): # -> Any:
        """
        5번 매크로 실행(Alt+Shift+#)

        """
        ...
    
    def ScrMacroPlay6(self): # -> Any:
        """
        6번 매크로 실행(Alt+Shift+#)

        """
        ...
    
    def ScrMacroPlay7(self): # -> Any:
        """
        7번 매크로 실행(Alt+Shift+#)

        """
        ...
    
    def ScrMacroPlay8(self): # -> Any:
        """
        8번 매크로 실행(Alt+Shift+#)

        """
        ...
    
    def ScrMacroPlay9(self): # -> Any:
        """
        9번 매크로 실행(Alt+Shift+#)

        """
        ...
    
    def ScrMacroPlay10(self): # -> Any:
        """
        10번 매크로 실행(Alt+Shift+#)

        """
        ...
    
    def ScrMacroPlay11(self): # -> Any:
        """
        11번 매크로 실행(Alt+Shift+#)

        """
        ...
    
    def ScrMacroRepeat(self): # -> Any:
        """스크립트 매크로 실행"""
        ...
    
    def ScrMacroStop(self): # -> Any:
        """
        매크로 기록 중지

        """
        ...
    
    def Select(self): # -> Any:
        """
        선택 (F3 Key를 누른 효과)

        """
        ...
    
    def SelectAll(self): # -> Any:
        """
        모두 선택(Ctrl-A)

        """
        ...
    
    def SelectColumn(self): # -> Any:
        """
        칸 블록 선택 (F4 Key를 누른 효과)

        """
        ...
    
    def SelectCtrlFront(self): # -> Any:
        """
        정방향으로 가장 가까운 컨트롤을 찾아 선택

        """
        ...
    
    def SelectCtrlReverse(self): # -> Any:
        """
        역방향으로 가장 가까운 컨트롤을 찾아 선택

        """
        ...
    
    def SendBrowserText(self): # -> Any:
        """
        브라우저로 보내기

        브라우저가 실행되고, 현재 문서가 브라우저에 나타난다.
        """
        ...
    
    def SetWorkSpaceView(self): # -> Any:
        """작업창 보기 설정"""
        ...
    
    def ShapeObjAlignBottom(self): # -> Any:
        """
        아래로 정렬

        """
        ...
    
    def ShapeObjAlignCenter(self): # -> Any:
        """
        가운데로 정렬

        """
        ...
    
    def ShapeObjAlignHeight(self): # -> Any:
        """
        높이 맞춤

        """
        ...
    
    def ShapeObjAlignHorzSpacing(self): # -> Any:
        """
        왼쪽/오른쪽 일정한 비율로 정렬

        """
        ...
    
    def ShapeObjAlignLeft(self): # -> Any:
        """
        왼쪽으로 정렬

        """
        ...
    
    def ShapeObjAlignMiddle(self): # -> Any:
        """
        중간 정렬

        """
        ...
    
    def ShapeObjAlignRight(self): # -> Any:
        """
        오른쪽으로 정렬

        """
        ...
    
    def ShapeObjAlignSize(self): # -> Any:
        """
        폭/높이 맞춤

        """
        ...
    
    def ShapeObjAlignTop(self): # -> Any:
        """
        위로 정렬

        """
        ...
    
    def ShapeObjAlignVertSpacing(self): # -> Any:
        """
        위/아래 일정한 비율로 정렬

        """
        ...
    
    def ShapeObjAlignWidth(self): # -> Any:
        """
        폭 맞춤

        """
        ...
    
    def ShapeObjAttachCaption(self): # -> Any:
        """
        역방향으로 가장 가까운 컨트롤에 캡션 추가

        캐럿 위쪽의 표, 이미지 등에 캡션을 생성한다.
        실행 후에는 캡션 안에 캐럿이 있으므로
        직접 insert_text 등으로 입력하고 CloseEx로 빠져나오면 된다.

        위쪽 컨트롤에 캡션이 있을 때에는 캡션 시작부분으로 진입한다.
        """
        ...
    
    def ShapeObjAttachTextBox(self): # -> Any:
        """
        사각형을 글상자로 변경

        사각형 선택 상태에서 실행하면 글을 삽입할 수 있게 된다.
        """
        ...
    
    def ShapeObjBringForward(self): # -> Any:
        """
        선택개체를 앞으로

        """
        ...
    
    def ShapeObjBringInFrontOfText(self): # -> Any:
        """
        선택개체를 글 앞으로

        """
        ...
    
    def ShapeObjBringToFront(self): # -> Any:
        """
        선택개체를 맨 앞으로

        """
        ...
    
    def ShapeObjCtrlSendBehindText(self): # -> Any:
        """
        선택개체를 글 뒤로

        """
        ...
    
    def ShapeObjDetachCaption(self): # -> Any:
        """
        캡션 없애기

        """
        ...
    
    def ShapeObjDetachTextBox(self): # -> Any:
        """
        글상자를 사각형으로 변경

        (주의)글상자 속의 텍스트는 사라짐
        """
        ...
    
    def ShapeObjFillProperty(self): # -> Any:
        """
        고치기 대화상자중 fill tab

        """
        ...
    
    def ShapeObjGroup(self): # -> Any:
        """
        틀 묶기

        """
        ...
    
    def ShapeObjHorzFlip(self): # -> Any:
        """
        그리기 개체 좌우 뒤집기

        """
        ...
    
    def ShapeObjHorzFlipOrgState(self): # -> Any:
        """
        그리기 개체 좌우 뒤집기를 원상태로 되돌리기

        """
        ...
    
    def ShapeObjInsertCaptionNum(self): # -> Any:
        """
        캡션 번호 넣기

        """
        ...
    
    def ShapeObjLineProperty(self): # -> Any:
        """
        고치기 대화상자중 line tab

        """
        ...
    
    def ShapeObjLock(self): # -> Any:
        """
        개체 Lock

        """
        ...
    
    def ShapeObjMoveDown(self): # -> Any:
        """
        키로 움직이기(아래)

        """
        ...
    
    def ShapeObjMoveLeft(self): # -> Any:
        """
        키로 움직이기(왼쪽)

        """
        ...
    
    def ShapeObjMoveRight(self): # -> Any:
        """
        키로 움직이기(오른쪽)

        """
        ...
    
    def ShapeObjMoveUp(self): # -> Any:
        """
        키로 움직이기(위)

        """
        ...
    
    def ShapeObjNextObject(self): # -> Any:
        """
        이후 개체로 이동(tab키)

        """
        ...
    
    def ShapeObjNorm(self): # -> Any:
        """
        기본 도형 설정

        """
        ...
    
    def ShapeObjPrevObject(self): # -> Any:
        """
        이전 개체로 이동(shift + tab키)

        """
        ...
    
    def ShapeObjResizeDown(self): # -> Any:
        """
        키로 크기 조절(shift + 아래)

        """
        ...
    
    def ShapeObjResizeLeft(self): # -> Any:
        """
        키로 크기 조절(shift + 왼쪽)

        """
        ...
    
    def ShapeObjResizeRight(self): # -> Any:
        """
        키로 크기 조절(shift + 오른쪽)

        """
        ...
    
    def ShapeObjResizeUp(self): # -> Any:
        """
        키로 크기 조절(shift + 위)

        """
        ...
    
    def ShapeObjRightAngleRotater(self): # -> Any:
        """
        90도 시계방향 회전

        """
        ...
    
    def ShapeObjRightAngleRotaterAnticlockwise(self): # -> Any:
        """
        90도 반시계 방향 회전
        """
        ...
    
    def ShapeObjRotater(self): # -> Any:
        """
        자유각 회전(회전중심 고정)

        """
        ...
    
    def ShapeObjSaveAsPicture(self): # -> Any:
        """
        개체를 그림으로 저장하기

        """
        ...
    
    def ShapeObjSelect(self): # -> Any:
        """
        틀 선택 도구

        """
        ...
    
    def ShapeObjSendBack(self): # -> Any:
        """
        개체를 뒤로 보내기
        """
        ...
    
    def ShapeObjSendToBack(self): # -> Any:
        """
        맨 뒤로
        """
        ...
    
    def ShapeObjTableSelCell(self): # -> Any:
        """
        표의 첫 번째 셀 선택

        테이블 선택상태에서 실행해야 한다.
        비슷한 명령어로 ``hwp.ShapeObjTextBoxEdit()``가 있다.
        ``hwp.ShapeObjTableSelCell()``이 셀블록상태인데 반해
        ``hwp.ShapeObjTextBoxEdit()``는 편집상태이다.
        """
        ...
    
    def ShapeObjTextBoxEdit(self): # -> Any:
        """
        표나 글상자 선택상태에서 편집모드로 들어가기

        표를 선택하고 있는 경우 A1 셀 안으로 이동한다.

        """
        ...
    
    def ShapeObjUngroup(self): # -> Any:
        """
        틀 풀기(그룹해제)

        """
        ...
    
    def ShapeObjUnlockAll(self): # -> Any:
        """
        개체 잠금해제(Unlock All)

        """
        ...
    
    def ShapeObjVertFlip(self): # -> Any:
        """
        그리기 개체 상하 뒤집기

        """
        ...
    
    def ShapeObjVertFlipOrgState(self): # -> Any:
        """
        그리기 개체 상하 뒤집기 원상태로 되돌리기

        """
        ...
    
    def ShapeObjWrapSquare(self): # -> Any:
        """
        직사각형

        """
        ...
    
    def ShapeObjWrapTopAndBottom(self): # -> Any:
        """
        자리 차지

        """
        ...
    
    def ShowAttributeTab(self): # -> Any:
        """속성 작업창 보이기/감추기"""
        ...
    
    def ShowBottomWorkspace(self): # -> Any:
        """아래쪽 작업창 보이기/감추기"""
        ...
    
    def ShowFloatTabFrame(self): # -> Any:
        """플로팅 작업창 보이기/감추기"""
        ...
    
    def ShowLeftWorkspace(self): # -> Any:
        """왼쪽 작업창 보이기/감추기"""
        ...
    
    def ShowRightWorkspace(self): # -> Any:
        """오른쪽 작업창 보이기/감추기"""
        ...
    
    def ShowScriptTab(self): # -> Any:
        """스크립트 작업창 보이기/감추기"""
        ...
    
    def ShowTopWorkspace(self): # -> Any:
        """위쪽 작업창 보이기/감추기"""
        ...
    
    def SoftKeyboard(self): # -> Any:
        """
        소프트키보드 보기 토글

        """
        ...
    
    def SpellingCheck(self): # -> Any:
        """
        맞춤법

        """
        ...
    
    def SplitAll(self): # -> Any:
        """창 가로 세로 나누기"""
        ...
    
    def SplitHorz(self): # -> Any:
        """창 가로로 나누기"""
        ...
    
    def SplitMainActive(self): # -> Any:
        """메모창 활성화"""
        ...
    
    def SplitMemo(self): # -> Any:
        """메모창 보이기/감추기"""
        ...
    
    def SplitMemoClose(self): # -> Any:
        """
        메모창 닫기

        """
        ...
    
    def SplitMemoOpen(self): # -> Any:
        """
        메모창 열기

        """
        ...
    
    def SplitVert(self): # -> Any:
        """창 세로로 나누기"""
        ...
    
    def StyleClearCharStyle(self): # -> Any:
        """
        글자 스타일 해제

        """
        ...
    
    def StyleCombo(self): # -> Any:
        """글자 스타일"""
        ...
    
    def StyleShortcut1(self): # -> Any:
        """
        스타일 단축키1

        """
        ...
    
    def StyleShortcut2(self): # -> Any:
        """
        스타일 단축키2

        """
        ...
    
    def StyleShortcut3(self): # -> Any:
        """
        스타일 단축키3

        """
        ...
    
    def StyleShortcut4(self): # -> Any:
        """
        스타일 단축키4

        """
        ...
    
    def StyleShortcut5(self): # -> Any:
        """
        스타일 단축키5

        """
        ...
    
    def StyleShortcut6(self): # -> Any:
        """
        스타일 단축키6

        """
        ...
    
    def StyleShortcut7(self): # -> Any:
        """
        스타일 단축키7

        """
        ...
    
    def StyleShortcut8(self): # -> Any:
        """
        스타일 단축키8

        """
        ...
    
    def StyleShortcut9(self): # -> Any:
        """
        스타일 단축키9

        """
        ...
    
    def StyleShortcut10(self): # -> Any:
        """
        스타일 단축키10

        """
        ...
    
    def TabClose(self): # -> Any:
        """
        현재 탭 닫기

        """
        ...
    
    def TableAppendRow(self): # -> Any:
        """
        표 안에서, 현재 행 아래에 새 행 추가

        """
        ...
    
    def TableSubtractRow(self): # -> Any:
        """
        표 안에서, 현재 행 삭제

        """
        ...
    
    def TableAutoFill(self): # -> Any:
        """표 자동 채우기"""
        ...
    
    def TableAutoFillDlg(self): # -> Any:
        """자동 채우기 창 열기"""
        ...
    
    def TableCellAlignCenterBottom(self): # -> Any:
        """셀 가운데 아래 정렬"""
        ...
    
    def TableCellAlignCenterCenter(self): # -> Any:
        """셀 가운데 정렬"""
        ...
    
    def TableCellAlignCenterTop(self): # -> Any:
        """셀 가운데 위 정렬"""
        ...
    
    def TableCellAlignLeftBottom(self): # -> Any:
        """셀 왼쪽 아래 정렬"""
        ...
    
    def TableCellAlignLeftCenter(self): # -> Any:
        """셀 왼쪽 가운데 정렬"""
        ...
    
    def TableCellAlignLeftTop(self): # -> Any:
        """셀 왼쪽 위 정렬"""
        ...
    
    def TableCellAlignRightBottom(self): # -> Any:
        """셀 오른쪽 아래 정렬"""
        ...
    
    def TableCellAlignRightCenter(self): # -> Any:
        """셀 오른쪽 가운데 정렬"""
        ...
    
    def TableCellAlignRightTop(self): # -> Any:
        """셀 가운데 오른쪽 정렬"""
        ...
    
    def TableCellBlock(self) -> bool:
        """
        셀 블록 상태로 전환

        Returns:
            성공시 True, 실패시 False를 리턴

        Examples:
            >>> from pyhwpx import Hwp
            >>> hwp = Hwp()
            >>> hwp.get_into_nth_table(0)  # 문서 첫 번째 표로 이동
            >>> hwp.TableCellBlock()  # 셀블록
            >>> hwp.TableCellBlockExtend()  # 셀블록 확장
            >>> hwp.TableCellBlockExtend()  # 전체 셀 선택
            >>> rgb = (50, 150, 250)
            >>> hwp.cell_fill(rgb)

        """
        ...
    
    def TableCellBlockCol(self): # -> Any:
        """
        표 안에서 현재 열(Column) 전체 선택

        """
        ...
    
    def TableCellBlockExtend(self): # -> Any:
        """
        셀 블록 연장(F5 + F5)

        실행 전 hwp.TableCellBlock()을 실행해야 한다.

        """
        ...
    
    def TableCellBlockExtendAbs(self): # -> Any:
        """
        셀 블록 연장(SHIFT + F5)

        """
        ...
    
    def TableCellBlockRow(self): # -> Any:
        """
        현재 셀이 포함된 행 전체 선택

        """
        ...
    
    def TableCellBorderAll(self): # -> Any:
        """
        모든 셀 테두리 toggle(있음/없음).

        셀 블록 상태일 경우에만 동작한다.

        """
        ...
    
    def TableCellBorderBottom(self): # -> Any:
        """
        가장 아래 셀 테두리 toggle(있음/없음).

        셀 블록 상태일 경우에만 동작한다.

        """
        ...
    
    def TableCellBorderDiagonalDown(self): # -> Any:
        """
        대각선(⍂) 셀 테두리 toggle(있음/없음).

        셀 블록 상태일 경우에만 동작한다.

        """
        ...
    
    def TableCellBorderDiagonalUp(self): # -> Any:
        """
        대각선(⍁) 셀 테두리 toggle(있음/없음).

        셀 블록 상태일 경우에만 동작한다.

        """
        ...
    
    def TableCellBorderInside(self): # -> Any:
        """
        모든 안쪽 셀 테두리 toggle(있음/없음).

        셀 블록 상태일 경우에만 동작한다.

        """
        ...
    
    def TableCellBorderInsideHorz(self): # -> Any:
        """
        모든 안쪽 가로 셀 테두리 toggle(있음/없음).

        셀 블록 상태일 경우에만 동작한다.

        """
        ...
    
    def TableCellBorderInsideVert(self): # -> Any:
        """
        모든 안쪽 세로 셀 테두리 toggle(있음/없음).

        셀 블록 상태일 경우에만 동작한다.

        """
        ...
    
    def TableCellBorderLeft(self): # -> Any:
        """
        가장 왼쪽의 셀 테두리 toggle(있음/없음)

        셀 블록 상태일 경우에만 동작한다.

        """
        ...
    
    def TableCellBorderNo(self): # -> Any:
        """
        모든 셀 테두리 지움.

        셀 블록 상태일 경우에만 동작한다.

        """
        ...
    
    def TableCellBorderOutside(self): # -> Any:
        """
        바깥 셀 테두리 toggle(있음/없음)

        셀 블록 상태일 경우에만 동작한다.

        """
        ...
    
    def TableCellBorderRight(self): # -> Any:
        """
        가장 오른쪽의 셀 테두리 toggle(있음/없음)

        셀 블록 상태일 경우에만 동작한다.

        """
        ...
    
    def TableCellBorderTop(self): # -> Any:
        """
        가장 위의 셀 테두리 toggle(있음/없음)

        셀 블록 상태일 경우에만 동작한다.

        """
        ...
    
    def TableColBegin(self): # -> Any:
        """
        셀 이동: 현재 행의 가장 왼쪽 셀로 이동

        """
        ...
    
    def TableColEnd(self): # -> Any:
        """
        셀 이동: 현재 행의 가장 오른쪽 셀로 이동

        """
        ...
    
    def TableColPageDown(self): # -> Any:
        """
        셀 이동: 현재 열의 맨 아래로 이동

        """
        ...
    
    def TableColPageUp(self): # -> Any:
        """
        셀 이동: 현재 열의 맨 위로 이동

        """
        ...
    
    def TableDeleteCell(self, remain_cell: bool = ...) -> bool:
        """
        셀 삭제

        셀블록 상태에서 실행해야 한다.
        행 또는 열 전체 선택상태에서는 해당 행/열을 제거한다.

        Args:
             remain_cell: 지울 때 빈 셀은 남겨둘 것인가? (기본값은 남겨두지 않음=False)

        Returns:
            성공시 True, 실패시 False를 리턴.

        """
        ...
    
    def TableDistributeCellHeight(self): # -> Any:
        """
        표 안에서 셀 높이를 같게

        """
        ...
    
    def TableDistributeCellWidth(self): # -> Any:
        """
        표 안에서 셀 너비를 같게

        """
        ...
    
    def TableDrawPen(self): # -> Any:
        """
        표 그리기

        """
        ...
    
    def TableDrawPenStyle(self): # -> Any:
        """표 그리기 선 모양"""
        ...
    
    def TableDrawPenWidth(self): # -> Any:
        """표 그리기 선 굵기"""
        ...
    
    def TableEraser(self): # -> Any:
        """
        표 지우개

        """
        ...
    
    def TableFormulaAvgAuto(self): # -> Any:
        """
        표 안에 블록 평균 수식 삽입

        """
        ...
    
    def TableFormulaAvgHor(self): # -> Any:
        """
        표 안에 가로 평균 수식 삽입

        """
        ...
    
    def TableFormulaAvgVer(self): # -> Any:
        """
        표 안에 세로 평균 수식 삽입

        """
        ...
    
    def TableFormulaProAuto(self): # -> Any:
        """
        표 안에 블록 자동곱 수식 삽입

        """
        ...
    
    def TableFormulaProHor(self): # -> Any:
        """
        표 안에 가로 곱 수식 삽입

        """
        ...
    
    def TableFormulaProVer(self): # -> Any:
        """
        표 안에 세로 곱 수식 삽입

        """
        ...
    
    def TableFormulaSumAuto(self): # -> Any:
        """
        표 안에 블록 합계 수식 삽입

        """
        ...
    
    def TableFormulaSumHor(self): # -> Any:
        """
        표 안에 가로 합계 수식 삽입

        """
        ...
    
    def TableFormulaSumVer(self): # -> Any:
        """
        표 안에 세로 합계 수식 삽입

        """
        ...
    
    def TableLeftCell(self): # -> Any:
        """
        셀 이동: 셀 왼쪽

        """
        ...
    
    def TableLowerCell(self): # -> Any:
        """
        셀 이동: 셀 아래

        """
        ...
    
    def TableMergeCell(self): # -> Any:
        """
        셀 합치기

        셀 병합(m)
        """
        ...
    
    def TableMergeTable(self): # -> Any:
        """
        표와 표 붙이기

        """
        ...
    
    def TableResizeCellDown(self): # -> Any:
        """
        셀 크기 변경: 셀 아래

        """
        ...
    
    def TableResizeCellLeft(self): # -> Any:
        """
        셀 크기 변경: 셀 왼쪽

        """
        ...
    
    def TableResizeCellRight(self): # -> Any:
        """
        셀 크기 변경: 셀 오른쪽

        """
        ...
    
    def TableResizeCellUp(self): # -> Any:
        """
        셀 크기 변경: 셀 위

        """
        ...
    
    def TableResizeDown(self): # -> Any:
        """
        셀 크기 변경: 셀 아래

        """
        ...
    
    def TableResizeExDown(self): # -> Any:
        """
        셀 크기 변경: 셀 아래.

        TebleResizeDown과 다른 점은
        셀 블록 상태가 아니어도 동작한다는 점이다.

        """
        ...
    
    def TableResizeExLeft(self): # -> Any:
        """
        셀 크기 변경: 셀 왼쪽.

        TableResizeLeft와 다른 점은 셀 블록 상태가 아니어도 동작한다는 점이다.

        """
        ...
    
    def TableResizeExRight(self): # -> Any:
        """
        셀 크기 변경: 셀 오른쪽.

        TableResizeRight와 다른 점은 셀 블록 상태가 아니어도 동작한다는 점이다.

        """
        ...
    
    def TableResizeExUp(self): # -> Any:
        """
        셀 크기 변경: 셀 위쪽.

        TableResizeUp과 다른 점은 셀 블록 상태가 아니어도 동작한다는 점이다.

        """
        ...
    
    def TableResizeLeft(self): # -> Any:
        """
        셀 크기 변경: 왼쪽

        """
        ...
    
    def TableResizeLineDown(self): # -> Any:
        """
        셀 크기 변경: 선아래

        """
        ...
    
    def TableResizeLineLeft(self): # -> Any:
        """
        셀 크기 변경: 선 왼쪽

        """
        ...
    
    def TableResizeLineRight(self): # -> Any:
        """
        셀 크기 변경: 선 오른쪽

        """
        ...
    
    def TableResizeLineUp(self): # -> Any:
        """
        셀 크기 변경: 선 위

        """
        ...
    
    def TableResizeRight(self): # -> Any:
        """
        셀 크기 변경: 우측으로

        """
        ...
    
    def TableResizeUp(self): # -> Any:
        """
        셀 크기 변경: 위로

        """
        ...
    
    def TableRightCell(self): # -> Any:
        """
        셀 이동: 셀 오른쪽

        """
        ...
    
    def TableRightCellAppend(self): # -> Any:
        """
        셀 이동: 셀 오른쪽에 이어서

        우측 셀로 이동하다 끝에 도달하면 다음 행의 첫 번째 셀로 이동.
        그리고 다음 행이 없는 경우에는 새 행을 아래 추가하고 첫 번째 셀로 이동.

        """
        ...
    
    def TableSplitCell(self, Rows: int = ..., Cols: int = ..., DistributeHeight: int = ..., Merge: int = ...) -> bool:
        """
        셀 나누기.

        Args:
            Rows: 나눌 행 수(기본값:2)
            Cols: 나눌 열 수(기본값:0)
            DistributeHeight: 줄 높이를 같게 나누기(0 or 1)
            Merge: 셀을 합친 후 나누기(0 or 1)
        """
        ...
    
    def TableSplitTable(self): # -> Any | Literal[False]:
        """
        표 나누기

        현재 캐럿이 있는 행을 포함한 아랫쪽 부분을 잘라서
        별도의 표로 만든다.

        셀 블록 상태에서는 작동하지 않는다. 일반 편집상태여야 한다.
        """
        ...
    
    def TableUpperCell(self): # -> Any:
        """
        셀 이동: 셀 위로

        """
        ...
    
    def TableVAlignBottom(self): # -> Any:
        """
        셀의 텍스트를 아래로 세로정렬

        """
        ...
    
    def TableVAlignCenter(self): # -> Any:
        """
        셀의 텍스트를 가운데로 세로정렬

        """
        ...
    
    def TableVAlignTop(self): # -> Any:
        """
        셀의 텍스트를 위로 세로정렬

        """
        ...
    
    def ToggleOverwrite(self): # -> Any:
        """
        Toggle Overwrite

        """
        ...
    
    def TopTabFrameClose(self): # -> Any:
        """위쪽 작업창 감추기"""
        ...
    
    def Undo(self): # -> Any:
        """
        실행 취소(Ctrl-Z)
        """
        ...
    
    def UnlinkTextBox(self): # -> Any:
        """
        글상자 연결 끊기
        """
        ...
    
    def VersionDeleteAll(self): # -> Any:
        """
        모든 버전정보 지우기
        """
        ...
    
    def VertScrollbar(self): # -> Any:
        """세로축 스크롤바 보이기/감추기"""
        ...
    
    def ViewIdiom(self): # -> Any:
        """
        상용구 보기

        """
        ...
    
    def ViewOptionCtrlMark(self): # -> Any:
        """
        조판 부호 보기 토글

        """
        ...
    
    def ViewOptionGuideLine(self): # -> Any:
        """
        안내선 보기 토글
        """
        ...
    
    def ViewOptionMemo(self): # -> Any:
        """
        메모 보이기/숨기기 토글

        ([보기-메모-메모 보이기/숨기기]메뉴와 동일)

        """
        ...
    
    def ViewOptionMemoGuideline(self) -> bool:
        """
        메모 안내선 표시 토글

        ([보기-메모-메모 안내선 표시]메뉴와 동일)

        """
        ...
    
    def ViewOptionPaper(self) -> bool:
        """
        쪽 윤곽 보기/숨기기 토글

        """
        ...
    
    def ViewOptionParaMark(self) -> bool:
        """
        문단 부호 보기/숨기기 토글

        """
        ...
    
    def ViewOptionPicture(self) -> bool:
        """
        그림 보이기/숨기기 토글

        ([보기-그림]메뉴와 동일)

        """
        ...
    
    def ViewOptionRevision(self) -> bool:
        """
        교정부호 보이기/숨기기 토글

        ([보기-교정부호]메뉴와 동일)

        """
        ...
    
    def ViewTabButton(self) -> bool:
        """
        문서탭 보이기/감추기 토글
        """
        ...
    
    def ViewZoomFitPage(self) -> bool:
        """화면 확대: 페이지에 맞춤"""
        ...
    
    def ViewZoomNormal(self) -> bool:
        """화면 확대: 폭에 맞춤"""
        ...
    
    def ViewZoomFitWidth(self) -> bool:
        """화면 확대: 폭에 맞춤"""
        ...
    
    def ViewZoomRibon(self) -> bool:
        """화면 확대"""
        ...
    
    def VoiceCommandConfig(self) -> bool:
        """
        음성 명령 설정
        """
        ...
    
    def VoiceCommandResume(self) -> bool:
        """
        음성 명령 레코딩 시작
        """
        ...
    
    def VoiceCommandStop(self) -> bool:
        """
        음성 명령 레코딩 중지
        """
        ...
    


